### ISSUE TITLE
Selecting a category after an arrival filter is applied resets it

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_skill_cms#1024]
**Actual Behaviour**
Clicking on a category when a arrival filter is applied resets the time filter.

**Expected Behaviour**
The arrival filter should persist.

**Would you like to work on the issue?**
Yes

**Comment by anshumanv** [comment]
@akshatnitd you have any fix for this in mind? I tried passing the timeFilter with the state in Link tag since the URL is changed but not being able to work this out, this has a relatively simple fix in redux when the language can just be stored in the store and can be used anywhere in the app. What do you think we should do about this?

**Comment by fragm3** [comment]
Fixed with Redux integration.
