### ISSUE TITLE
Fix bug with fetching user's name

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_skill_cms#1026]
**Actual Behaviour**

When the user's name is not set, it is giving an error.

**Expected Behaviour**

Check if the user's name exists or not. Then assign it.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/17807257/42450281-40ded948-83a1-11e8-8692-4d81d6198aba.png)

**Would you like to work on the issue?**

Yes

**Comment by anshumanv** [comment]
Are you able to login locally?
