### ISSUE TITLE
Correct the hover color of `< SUSI Skills` on sidebar

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/susi_skill_cms#1048]
**Actual Behaviour**

The current hover color does not match with our theme. 

**Expected Behaviour**

The hover color should match with the theme. It should be the same as that on `clear`.

**Screenshots of the issue**

<img width="131" alt="screen shot 2018-07-10 at 8 23 27 pm" src="https://user-images.githubusercontent.com/31135861/42518336-39f5f452-847f-11e8-8288-b78296f9792e.png">

<img width="169" alt="screen shot 2018-07-10 at 8 27 36 pm" src="https://user-images.githubusercontent.com/31135861/42518566-baa09512-847f-11e8-87da-32bac36846e6.png">

**Would you like to work on the issue?**

Yes

**Comment by anshumanv** [comment]
@Akshat-Jain this forms a part of one of my action items as per the meeting, I'll be fixing this soon. :+1:

**Comment by anshumanv** [comment]
Or you can fix this real quick. :+1: :100:
