### ISSUE TITLE
Fix mobile version of start and cat pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#1095]
Compare Alexa mobile pages and SUSI.AI. Ensure the following works:
* [x] Cards use space until screen edge
* [x] Categories show up similar to Alexa
* [ ] Footer uses full available space same as https://chat.susi.ai/overview

![screenshot_2018-07-13-16-28-23-041_com android chrome](https://user-images.githubusercontent.com/1583873/42696971-149c2612-86ba-11e8-9b45-6b6d3a802e4f.png)

![screenshot_2018-07-13-16-28-51-901_com android chrome](https://user-images.githubusercontent.com/1583873/42696977-1a19b19a-86ba-11e8-92ca-d17e71d69ab3.png)

**Comment by Akshat-Jain** [comment]
I'm working on the first sub-issue.

**Comment by fragm3** [comment]
Working on 3rd part

**Comment by akshatnitd** [comment]
Working on the 2nd part.

**Comment by fragm3** [comment]
Not working, anyone is free to take this
