### ISSUE TITLE
Give users option to switch between `All` and `Reviewed Only` Skills on category pages

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/susi_skill_cms#1127]
**Actual Behaviour**

Currently, no such feature is there.

**Expected Behaviour**

As discussed in the meeting, this should be implemented.

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
@Akshat-Jain @mariobehling For this issue, shouldn't we display the reviewed skills only to all the users and keep this option for the Admin Section, where the author can review the skill and then approve it, after which it could be seen by all the users.
