### ISSUE TITLE
Improve design of cat and search list view in large resolutions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#1129]
Please change the design of the list view as following in large resolutions:

* Keep skill details next to each other (like Alexa)
* Make lines between areas have some space 
* For list and grid view use the same top bar blue instead of current blue
* Change font size of Sorty by "Feedback" and Languages "English" drop-down display to the same as the font in the left sidebar (e.g. as in "Last 7 days")
* Link "Skill Icon" to the skill page
* Fix all skill icon images to be square and have their natural ratio/dimensions e.g. https://skills.susi.ai/Communication/TELL_ME_TIME/en
* Show info about page in page html title to ensure it shows up in browser header, e.g. for cat communication like "SUSI.AI - Communication Skills"
![screenshot from 2018-07-16 20-08-00](https://user-images.githubusercontent.com/1583873/42775166-ff309fd4-8933-11e8-862f-784e2dd58fe3.png)

![screenshot from 2018-07-16 19-55-47](https://user-images.githubusercontent.com/1583873/42774707-afb3f72c-8932-11e8-89c5-06e66dc82c2a.png)

![screenshot from 2018-07-16 19-55-24](https://user-images.githubusercontent.com/1583873/42774720-b924faea-8932-11e8-90f2-1577c92f574b.png)

**Comment by fragm3** [comment]
Working on it, wont take much time.

**Comment by fragm3** [comment]
Working on last one: Show info about page in page html title to ensure it shows up in browser header, e.g. for cat communication like "SUSI.AI - Communication Skills"

**Comment by fragm3** [comment]
@mariobehling Fix all skill icon images to be square and have their natural ratio/dimensions is correct, no need to fix this.

**Comment by mariobehling** [comment]
> Fix all skill icon images to be square and have their natural ratio/dimensions e.g. https://skills.susi.ai/Communication/TELL_ME_TIME/en

This is not fixed yet, e.g. compare image ratio here. It is squeezed!
https://skills.susi.ai/Knowledge/language_!/en
and open the image in a new tab: https://raw.githubusercontent.com/fossasia/susi_skill_data/master/models/general/Knowledge/en/images/profaneLanguage.jpg

**Comment by fragm3** [comment]
@mariobehling is this whats needed?
<img width="800" alt="screen shot 2018-07-21 at 2 11 18 pm" src="https://user-images.githubusercontent.com/18073126/43033894-0b6df340-8cf0-11e8-82c5-431c8a0be509.png">
