### ISSUE TITLE
Botbuilder: In Wizard Step 3/Configure - add "Enable device for my devices", "Enable device for users: ...."

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#1131]
In the Botbuilder: In Wizard Step 3/Configure - add "Enable device for my devices", "Enable device for users: ...."

It should be possible to use "private skills" on a users own devices. Also it should be possible to allow other users to use the skill. Later on, users could enable skills even for groups, e.g. friends.

As a first step, please implement a tick box for these functionalities in the configure tab in the wizard.

**Comment by DNS-404** [comment]
I'd like to work on this. 👍
