### ISSUE TITLE
Add admin settings tab

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#1136]
The admin settings tab should show all kinds of config and keys eg. Mail settings like sendgrid, storage locations, map keys etc. Please implement it.

**Comment by tathagat2006** [comment]
@mariobehling Can I work on this issue?

**Comment by AnuragGupta93** [comment]
@mariobehling Is this issue still going on? I would like to solve to issue. Would you please assign it to me?

**Comment by harsh-jindal** [comment]
@mariobehling This issue seems to be fixed and currently under admin settings we are displaying the config keys. I suppose further discussion on this issue shall be done in accounts.susi.ai repo.
