### ISSUE TITLE
Add feature of saving draft of chatbot

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi_skill_cms#1142]
**Actual Behaviour**

Currently, if you close your browser tab in between the process of creating your bot, no draft is saved and all the process is lost.

**Expected Behaviour**

A draft of the bot should be saved at that time. This draft bot will be visible under "My bots" and will allow user to continue creating chatbot from where he left it.

**Would you like to work on the issue?**

Yes

**Comment by Orbiter** [comment]
The draft back-end storage is implemented, see https://github.com/fossasia/susi_server/issues/994
