### ISSUE TITLE
UI issues in sidebar and footer.

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_skill_cms#1151]
**Actual Behaviour**
* Fix divider on sidebar and remove extra border.
* Make the footer similar to https://chat.susi.ai/overview

**Would you like to work on the issue?**
Yes

**Comment by anshumanv** [comment]
@akshatnitd can you help me understand the 1st point `FIx divider ..` as discussed in the meeting? Do we want to remove it?

**Comment by anshumanv** [comment]
Thanks for explaining @akshatnitd, I'll fix this today.

**Comment by anshumanv** [comment]
@akshatnitd fixing the sidebar issues, can you please look into the footer part as I'm experiencing some issues while fixing it.

**Comment by aashutoshrathi** [comment]
@mariobehling @anshumanv This should be closed now?

**Comment by anshumanv** [comment]
Footer seem to still have some issues(not exactly same), compare it with the one on chat.susi

**Comment by sk9331657** [comment]
@anshumanv  Can you please point out differences between them ?? There is the only a difference of alignment between the items.

**Comment by anshumanv** [comment]
They should be the same components ideally and should behave the same. Introspect.
