### ISSUE TITLE
BotBuilder Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_skill_cms#1164]
**Actual Behaviour**

Error on undefined

**Expected Behaviour**

No error

**Screenshots of the issue**

<img width="903" alt="screen shot 2018-07-17 at 12 04 41 pm" src="https://user-images.githubusercontent.com/18073126/42822813-a2e46c1c-89f9-11e8-938c-5073ebf5e98d.png">

**Would you like to work on the issue?**

Yes

**Comment by anshumanv** [comment]
Please try to fix this too - 
![image](https://user-images.githubusercontent.com/21009455/42857941-be1e0144-8a69-11e8-8aaa-4f22461877e2.png)

**Comment by fragm3** [comment]
On it
