### ISSUE TITLE
Name not available on Skills Card and Skills List

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_skill_cms#1178]
**Actual Behaviour**

Name not available shows up

**Expected Behaviour**

Show loading till names are not fetched.

**Screenshots of the issue**

<img width="700" alt="screen shot 2018-07-18 at 1 30 29 pm" src="https://user-images.githubusercontent.com/18073126/42870685-1861b020-8a96-11e8-822d-cb285a57d798.png">
<img width="700" alt="screen shot 2018-07-18 at 2 20 34 pm" src="https://user-images.githubusercontent.com/18073126/42870686-18a5d30e-8a96-11e8-918d-1432c143f39c.png">

**Would you like to work on the issue?**

Yes

**Comment by sk9331657** [comment]
@fragm3  Can I work on this??

**Comment by sk9331657** [comment]
@akshatnitd  @Akshat-Jain This can be closed now.
