### ISSUE TITLE
Remove admin panel from cms and redirect to account

### ISSUE THREAD

**Issue by PrP-11** [fossasia/susi_skill_cms#1184]
**Actual Behaviour**
There are two admin panels for SUSI.

**Expected Behaviour**
- We should have a single admin panel to manage all admin content similar to other projects
- Add link to accounts' admin panel like https://github.com/fossasia/chat.susi.ai/pull/1465

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
Please keep it in the CMS for now. This should not be a problem as it is mainly code duplication. Also it seems handy to have a control over skills by admins in the same place as users for now. We need to think this though before we change it. It can be in two places for now.
