### ISSUE TITLE
Changing a skill's example is not reflected immediately

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#1186]
I changed the example of the skill CEO and both examples - the old one and the new one showed up. Expected: Only the new one should show up.

![screenshot from 2018-07-18 21-24-56](https://user-images.githubusercontent.com/1583873/42903161-39bd39d4-8ad1-11e8-8133-b1c6fe6db362.png)

**Comment by akshatnitd** [comment]
This has been solved
