### ISSUE TITLE
Prefill "Commit Message"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#1190]
On Github the commit message is prefilled with some basics in case devs don't want to fill in anything. In that case the code is stored with the standard commit message. Please implement the same. Fill in the commit message as follows:

"Updated Skill {Skill Name Here}"

![screenshot from 2018-07-18 21-36-51](https://user-images.githubusercontent.com/1583873/42903618-ba817d7c-8ad2-11e8-9596-657323b82673.png)

**Comment by hkedia321** [comment]
Working on this.
