### ISSUE TITLE
Add "updated skills" and correct "latest skills" to not include updated to start page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#1204]
Latest skills on start page also shows "updated skills" as latest skills: Expected:
* Show only new latest skills as "latest skills"
* Add a row of "updated skills" - SUSI, what skills were recently updated?

**Comment by fragm3** [comment]
This issue is merged, please close this

**Comment by akshatnitd** [comment]
Also done. Hence, closing.
