### ISSUE TITLE
System often make caps to lower case

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#1205]
System should always respect lower and upper case, e.g. authors on the skills and cat pages.

![screenshot from 2018-07-19 10-20-54](https://user-images.githubusercontent.com/1583873/42930548-9457a71e-8b3d-11e8-886a-bf4752c27e20.png)

**Comment by Akshat-Jain** [comment]
Working on it.

**Comment by Akshat-Jain** [comment]
@mariobehling I think this issue can be closed now as it has been resolved by this PR on server (https://github.com/fossasia/susi_server/pull/1015). It has been merged and you can also see the changes on CMS. Thanks :-)
