### ISSUE TITLE
Implement additional comments page for skills

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#1211]
All comments and feedback are currently kept on the skills page itself. What if a skill has thousands of feedback comments? Please implement a separate page for comments similar to Amazon. When the user clicks on "more" they should be directed to another page with more information. This page should also be paginated, e.g. keep 20 reviews per page.

**Comment by fragm3** [comment]
I would like to work on this.

**Comment by akshatnitd** [comment]
This has been resolved. Hence, closing.
