### ISSUE TITLE
Implement Staff Picks on Start Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#1217]
Staff Picks should be a state of a skill that could be set by admins of the system.

Please implement this. Open required issues in the server.

**Comment by akshatnitd** [comment]
Will do it, as soon as https://github.com/fossasia/susi_server/issues/1033 gets merged.

**Comment by Akshat-Jain** [comment]
@akshatnitd I think you can proceed with implementing Staff Picks on the CMS Homepage. All work required on the Server side and in the Admin panel has been done. Thanks :-)
