### ISSUE TITLE
Admin page displays 404 while the content is being loaded

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/susi_skill_cms#1219]
**Actual Behaviour**
Currently, we're displayed a 404 page while the contents of the Admin page are loaded.

**Expected Behaviour**
A circular loader can be shown by the time the contents are loaded on the Admin page.

**Would you like to work on the issue?**
Yes

**Comment by anshumanv** [comment]
@Akshat-Jain I sent a PR for this already and I'll be opening this - https://github.com/fossasia/susi_skill_cms/pull/1196

Since the discussion about shifting admin page is kept on hold.

Duplicate of https://github.com/fossasia/susi_skill_cms/issues/1171

**Comment by Akshat-Jain** [comment]
@anshumanv Thanks for pointing it out. Closing this issue. Thanks :-)
