### ISSUE TITLE
Improve Botbuilder Wizard Step 3

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#1237]
Please implement the following for Botbuilder Wizard Step 3:
* Show tick box "Allow bot only on own site"
  * If the user ticks the box, show table where the use can enter domains
  * Improve the current table: Use more visible colors for heading, take out placeholders, add a [+] button to enter more domains
* Add additional information what the options mean as a small info text below the options:
  * Include SUSI default skills
  * Enable bot in my devices
  * Enable bot for other users

**Comment by DNS-404** [comment]
Working on it. 👍
