### ISSUE TITLE
Optimise botbuilder images

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_skill_cms#1239]
**Actual Behaviour**

Images which are being used for the bot templates are not all in the same size and too big.

**Expected Behaviour**

The images need to be optimized to the size that they are used in the system without appearing distorted or pixelated.

**Screenshot for the issue**
![image](https://user-images.githubusercontent.com/17807257/43039943-7e938cd0-8d55-11e8-934d-8101f84540ac.png)

**Would you like to work on the issue?**

Yes

**Comment by starlord1311** [comment]
@hkedia321 @mariobehling can i take up this issue?

**Comment by hkedia321** [comment]
@starlord1311 Okay, please go ahead. The images are in https://github.com/fossasia/susi_skill_cms/tree/master/public/botTemplates

**Comment by starlord1311** [comment]
can you tell how am i supposed to do it? @hkedia321
