### ISSUE TITLE
Use same colors for buttons across botbuilder

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#1242]
Please use gray for inactive elements and blue for active elements, e.g. the view that is active.

![screenshot from 2018-07-21 13-16-04](https://user-images.githubusercontent.com/1583873/43035044-5cb36c56-8ce8-11e8-87a5-1b4b045daee7.png)

**Comment by DNS-404** [comment]
Working on it. 👍

**Comment by DNS-404** [comment]
Okay. Working on it. 👍
