### ISSUE TITLE
Remove .txt from the skills name

### ISSUE THREAD

**Issue by saurabhjn76** [fossasia/susi_skill_cms#126]
Currently,txt extension is appended in skill name
![image](https://user-images.githubusercontent.com/9781788/28501473-e56a3276-6ff9-11e7-8629-46989d1f1de8.png)
Remove .txt from the skill name

**Comment by zamhaq** [comment]
Hello Can I contribute to this project ? I am new to open source. I could not find the gitter channel so I am commenting here. Can I work on this ?

**Comment by saurabhjn76** [comment]
Hello @zamhaq, we would love to have your contributions, please join our gitter channel [https://gitter.im/fossasia/susi_server](https://gitter.im/fossasia/susi_server)
