### ISSUE TITLE
Make the deployment section similar to intercom.com

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_skill_cms#1290]
**Actual Behaviour**

The deployment section of the botbuilder contains just the javascript link generated and not step wise instructions.

**Expected Behaviour**

It should contain step wise information, similar to that of intercom:
![image](https://user-images.githubusercontent.com/17807257/43116084-b1049be4-8f23-11e8-9763-b76516f38ecf.png)

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Thanks for the first step in making this happen. Please make the implementation more similar to the above screenshot and avoid making everything bold. Thank you.
