### ISSUE TITLE
Refactor the code components

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_skill_cms#1291]
**Actual Behaviour**
* The code needs refactoring and duplicate code needs to be removed.
* Structure of files needs to be changed

**Expected Behaviour**
* The codebase to become more organised.

**Would you like to work on the issue?**
Yes

**Comment by anshumanv** [comment]
Refactoring skill rating card.

**Comment by anshumanv** [comment]
Refactoring SkillUsageCard
