### ISSUE TITLE
Add "test examples" link functionality to overview category pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#1298]
At the moment examples can only be tried out from the specific skill page. Please also make this work from the category pages.

![screenshot from 2018-07-24 19-39-55](https://user-images.githubusercontent.com/1583873/43156101-864eb1cc-8f79-11e8-8b03-8df29d38c5ec.png)

**Comment by akshatnitd** [comment]
Working on it
