### ISSUE TITLE
Use skill name on skill pages instead of skill tags

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_skill_cms#1328]
**Actual Behaviour**
Skill tags are used for skill page header

**Expected Behaviour**
Need to use skill Name.

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/21009455/43299811-8f8f7b20-9179-11e8-8174-880b69db9da4.png)

**Would you like to work on the issue?**
Yes

**Comment by anshumanv** [comment]
@akshatnitd @AnupKumarPanwar is it intentional to show skill tag or I can go ahead with this?

**Comment by akshatnitd** [comment]
Skill name should be shown.
