### ISSUE TITLE
Enhance Skill Feedback Page

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_skill_cms#1335]
**Actual Behaviour**

Not present

**Expected Behaviour**

- [x] Scroll to feedback section on page change

- [x] Previous or next disabled on first, last page respectively

- [x] Editing current feedback gives bug

<img width="571" alt="screen shot 2018-07-27 at 6 14 37 pm" src="https://user-images.githubusercontent.com/18073126/43321294-089fe32a-91c9-11e8-8376-d30584786bbe.png">

- [ ] Customer review next to skill name (like here: https://www.amazon.com/Amazon-Twenty-Questions/product-reviews/B01C3CO48G/ref=cm_cr_othr_d_paging_btm_1?ie=UTF8&reviewerType=all_reviews&pageNumber=1)

**Would you like to work on the issue?**

Yes

**Comment by anshumanv** [comment]
Awesome, can you also make sure that `Next` and `Previous` button are not visible on the first and last page respectively?

**Comment by fragm3** [comment]
@anshumanv yes thats point#2

**Comment by anshumanv** [comment]
Ah okay, in that case make sure they work in firefox as they won't work for me, both the buttons, can you please test as well?
