### ISSUE TITLE
Implement delete account feature

### ISSUE THREAD

**Issue by PrP-11** [fossasia/susi_skill_cms#1349]
**Actual Behaviour**
Admins cannot delete user account

**Expected Behaviour**
Implement feature to delete a user account on users tab
Server PR : https://github.com/fossasia/susi_server/pull/1087

**Would you like to work on the issue?**
Yes

**Comment by Akshat-Jain** [comment]
@PrP-11 We need to keep the two Admin panels aligned as soon as anything is merged in one repo. Please don't make issues and then not work on them. If you're not working on this, can I work on this?

**Comment by anshumanv** [comment]
This should be done asap I believe.
