### ISSUE TITLE
Display devices of users on admin panel

### ISSUE THREAD

**Issue by PrP-11** [fossasia/susi_skill_cms#1351]
**Actual Behaviour**
Devices info of users is not displayed on users tab

**Expected Behaviour**
Display devices of users along with other details

**Would you like to work on the issue?**
Yes

**Comment by akshatnitd** [comment]
How are you planning to do it?

**Comment by PrP-11** [comment]
same as https://github.com/fossasia/accounts.susi.ai/pull/380
