### ISSUE TITLE
Add tooltips for category names in author skills

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_skill_cms#1354]
**Actual Behaviour**
No tooltips present so some categories are not visible all the time as depicted in the screenshot.

**Expected Behaviour**
Add tooltips

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/21009455/43362690-695bc882-930e-11e8-8ecb-dbae51771948.png)

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
Extensive tool tips are not standard user experience on many areas. Please avoid too many tooltips. It is also not suitable for mobiles.
