### ISSUE TITLE
Image not working in Editor Window

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#1382]
The editor window does not show the skill image from SUSI.AI, because of an 503.

![screenshot from 2018-07-31 18-41-00](https://user-images.githubusercontent.com/1583873/43455079-63f65102-94f1-11e8-8d22-2d88465b355f.png)

https://api.susi.ai/cms/getImage.png?model=general&language=undefined&group=undefined&image=images/tweets.png

![screenshot from 2018-07-31 17-51-18](https://user-images.githubusercontent.com/1583873/43455090-6c482718-94f1-11e8-8f41-3d794c15df7c.png)

**Comment by DNS-404** [comment]
Okay. Working on it. 👍
