### ISSUE TITLE
add read more button if there are long list of queries 

### ISSUE THREAD

**Issue by isuruAb** [fossasia/susi_skill_cms#1410]
**Actual Behaviour**

some skills have a long list of queries. ex: https://skills.susi.ai/Weather/weather_information/en

**Expected Behaviour**

If we can add a read more button and hide a few queries that would be good.

**Screenshots of the issue**

<img width="1260" alt="screen shot 2018-08-02 at 10 21 19 am" src="https://user-images.githubusercontent.com/7692626/43558836-fa909a1c-963d-11e8-8b17-e2d53f764611.png">

**Comment by fragm3** [comment]
Working on this.
