### ISSUE TITLE
Make the private skill icon upload optional

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi_skill_cms#1429]
**Actual Behaviour**

Currently, it is necessary to upload an image in order to create a private skill.

**Expected Behaviour**

This should not be the case. Rather, if the user doesn't provide a custom image for private skill then the SUSI image should be used.

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
This solves the first step of making it optional, but the way it is displayed might confuse users as it does not show a + sign here, that users can upload their own image here. So, only display the SUSI logo on the skills page, but on the edit/create page please add the + image.
