### ISSUE TITLE
Fetch data for tree and conversation view rather than generating it through code view

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi_skill_cms#1431]
**Expected Behaviour**

We need to fetch SUSI response for conversation and tree view from server using `instant` parameter rather than generating this data from code view.
Reference commit: https://github.com/fossasia/susi_server/commit/11beea0bf655a4deeed3637a6c41bb2432750d4d

**Would you like to work on the issue?**

Yes

**Comment by DNS-404** [comment]
@hkedia321 Regarding the implementation of this issue, if we fetch response for user queries from server than the conversation view will turn out to be really slow. As this is a view and not the preview, hence we would have to display responses of all the user queries specified in code view. This will require us to make many calls to server for response of **each** user query written in the code view.
Whereas the current implementation simply converts the code in state of code view to "conversation" which is then displayed in conversation view. This is done almost instantly.
Hence, I don't think that implementing this the way written in this issue would be good. What do you think about this?

**Comment by hkedia321** [comment]
@DNS-404 Yes, I agree fetching responses from the server for each and every query will be too slow. We can reduce some time by fetching all the responses asynchronously. Though we can generate the views locally by processing the texts, it may get increasingly complex further on, when new syntaxes are added in SUSI Skill language (such as support for images, conversational structure, etc). I think we should go with fetching the responses from the server for each query, keeping in mind the long term advantages. Though I am not sure about this. Let @Orbiter @mariobehling confirm on this. Thanks!

**Comment by DNS-404** [comment]
> Though we can generate the views locally by processing the texts, it may get increasingly complex further on, when new syntaxes are added in SUSI Skill language (such as support for images, conversational structure, etc). I think we should go with fetching the responses from the server for each query, keeping in mind the long term advantages.

Agreed. Thanks! Alright, I'll implement this.
