### ISSUE TITLE
Use Link in Skill image in author skills component

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_skill_cms#1447]
**Actual Behaviour**
`a` tag is used.

**Would you like to work on the issue?**
Yes

**Comment by anshumanv** [comment]
@akshatnitd @Akshat-Jain on changing to link the page no longer changes for me, can you cross check?

**Comment by harsh-jindal** [comment]
@anshumanv This issue is fixed. Now in SkillCardList.js the image uses "Link" component.
