### ISSUE TITLE
Add jumpers to tables in Admin Panel

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/susi_skill_cms#1477]
**Actual Behaviour**
There is no option to go to a page directly in the tables in the Admin Panel.

**Expected Behaviour**
There should be an option to jump to a page directly.
Corresponding issue on accounts repo: https://github.com/fossasia/accounts.susi.ai/issues/418

**Would you like to work on the issue?**
Yes

**Comment by PrP-11** [comment]
@Akshat-Jain I am working on this already on both pages. A lot of times you just open same issues opened by others of different repos without asking whether they are working on it or not.

**Comment by Akshat-Jain** [comment]
@PrP-11 I didn't see any issue opened on this repo by you. Hence I opened the issue and I'm working on it. Please open issues in both repos otherwise how would others know if you're working on it on this repo? Thanks :-)

**Comment by PrP-11** [comment]
@Akshat-Jain I was going to open the issue when the PR on accounts gets merged. Also the point here is that if someone find an issue and they opened it somewhere then you must ask them before working on it. This is a general practice we should follow in the community.
