### ISSUE TITLE
Place for storing susi_skill images

### ISSUE THREAD

**Issue by saurabhjn76** [fossasia/susi_skill_cms#152]
We need to decide the place to store skill images.
One way is to 
- Host image on a free image hosting website and provide a link: This is not suitable since depending on another website would mean if the website goes down, skill image would not be available in skill_cms. Also security vulnerabilities, people can inject malicious` img` looking scripts and link them to load for the clients. So image data must be stored in the repository itself. The maximum prescribed size of a Github Repo is 1GB.There can be a problem in future if we have too many skills.

Provide views on adding images through skill editor and place for storing the images.

**Comment by mariobehling** [comment]
Store the image in the repo. Propose standard image sizes. Check what Amazon Alexa needs and follow this approach.

**Comment by saurabhjn76** [comment]
All images are stored in susi_skill_data repository
