### ISSUE TITLE
Remove animation from view buttons

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi_skill_cms#1548]
**Actual Behaviour**

The icons for code view, conversation view and tree view on Build tab of botbuilder has an animation for helper text on hover. Same is for Code view and UI view on Design tab and Configure tab.

**Expected Behaviour**

These animations need to be removed.

**Screenshots of the issue**

<img width="157" alt="screen shot 2018-08-14 at 7 19 03 pm" src="https://user-images.githubusercontent.com/31174685/44095639-f6a8ede2-9ff6-11e8-8df1-e8accace71bf.png">

**Would you like to work on the issue?**

This is a small issue good for beginners. So if anyone wants to take this up, just comment here and then send a PR.

**Comment by SanjanaSanikommu** [comment]
I would like to work on this issue

**Comment by SanjanaSanikommu** [comment]
I would like to work on this issue.

**Comment by jeswincyriac** [comment]
Let me try this,if no one is working on this.

**Comment by SanjanaSanikommu** [comment]
Yes, you can work on this

**Comment by sk9331657** [comment]
@DNS-404  Shall I proceed as it seems no one is working on it.

**Comment by DNS-404** [comment]
@sk9331657 Sure, go ahead. It seems like this issue isn't so simple. Please ask if you face any problems.

**Comment by tathagat2006** [comment]
@DNS-404  Can I work on this issue, if it hasn't been closed or no one else is working on it?

**Comment by sk9331657** [comment]
@DNS-404  I am working on this.
