### ISSUE TITLE
Make the same background color for all popups

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_skill_cms#1549]
**Actual Behaviour**

Several popups exists, many are having different background colors. Also make effect fast and avoid any effects like "unfolding effect" or others.

**Expected Behaviour**

The popups should have the same grey background color.

**Screenshots of the issue**

![screenshot from 2018-08-14 19-21-01](https://user-images.githubusercontent.com/17807257/44095812-5b5886b2-9ff7-11e8-8d1a-2fc91d7c171f.png)
![popup color](https://user-images.githubusercontent.com/17807257/44095873-819c851c-9ff7-11e8-8a00-3412a372c409.png)

**Would you like to work on the issue?**

No, anyone can take this up.

**Comment by SanjanaSanikommu** [comment]
I would like to work on this issue

**Comment by aashutoshrathi** [comment]
Claiming this

**Comment by lakshaysharma14** [comment]
I would like to take this issue.

**Comment by anshumanv** [comment]
Hey @lakshaysharma14 thanks for your interest, however, @aashutoshrathi is already working on this, meanwhile you can lookup some other issues. :+1:

**Comment by aashutoshrathi** [comment]
@hkedia321 most of them have a black background already. 😕

**Comment by AdityaSrivast** [comment]
@hkedia321 Can I take up this issue?

**Comment by sk9331657** [comment]
@hkedia321  Can you point where background color is different??

**Comment by sk9331657** [comment]
@anshumanv  Here also, I can't figure out any different backgound.

**Comment by anshumanv** [comment]
@hkedia321 please check once if this still persists.

**Comment by hkedia321** [comment]
Not needed now.
