### ISSUE TITLE
Display bot icon while listing all bots of the user

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_skill_cms#1551]
**Actual Behaviour**

Bot icon not getting displayed in the list private bots section (https://skills.susi.ai/botbuilder)

**Expected Behaviour**

Bot icon should be displayed inside each card. 
Bot icons are given by the skill creator, when the skill is being created:
![image](https://user-images.githubusercontent.com/17807257/44995867-a1ed4d80-afc2-11e8-8d41-8385ae2b509e.png)
Bot icons can be accessed by using the `getImage.png` API with the following get parameters:
- `access_token`: the access token of the currently logged user
- `language`: the language of the skill
- `group`: group name of the skill
- `image`: image name for the skill

Example: `https://api.susi.ai/cms/getImage.png?access_token=<access_token>&language=en&group=Business%20and%20Finance&image=images/elon%20musk%20car.jpg`

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/17807257/44096475-f7e62812-9ff8-11e8-8bea-d6aaa966069e.png)

The bot icon for each skill card should be displayed on it.

**Would you like to work on the issue?**

No, anyone can take this up. If you have any doubts please ask below.

**Comment by AdityaSrivast** [comment]
I want to work on this issue. May I take this up?

**Comment by hkedia321** [comment]
@AdityaSrivast Yes, please go ahead.
