### ISSUE TITLE
Simplify Skill CMS. Improve design. Delete left sidebar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#156]
Please do the following:
**Left Sidebar**
* Delete browse skills. It is not needed as the SUSI.AI logo already leads to the front page with the same content.
* Delete section and feature "Browse Examples". This should be covered by search later.
* Delete Visual Skill Editor. It is unclear what it is needed for and why it is on the sidebar.
* Delete Browse Skill Revision. It does not belong into the sidebar.

**Chat integration**
* Delete SUSI Web Chat integration. The integration is buggy and does not fulfill our needs.

**Top bar**
* Reuse the top bar from the chat page, but position the logo on the left
* Use same dropdown menu and functionality as on web chat with the tabs the same 
![screenshot from 2017-07-30 00-37-25](https://user-images.githubusercontent.com/1583873/28749175-497d4b9e-74bf-11e7-985a-e46490543513.png)
* Delete Wikipedia message, which is there for no reason
![screenshot from 2017-07-30 00-50-30](https://user-images.githubusercontent.com/1583873/28749241-2941b76e-74c1-11e7-9d36-988eeeb0463d.png)

**Other**
* Add a settings page at `/settings`. This page can be blank for now. We can follow up in a separate issue.

**Comment by uday96** [comment]
Will work on this :+1:
