### ISSUE TITLE
Implement skill page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#158]
When a user clicks on a skill e.g. on the front page, the user should first get an overview of the skill and related data. 

* Please implement an specific skill page with the basic data following the Alexa approach.
* Add a button "Edit" on the top right directing the user to the skill edit page
![screenshot from 2017-07-30 01-32-19](https://user-images.githubusercontent.com/1583873/28749435-6a906606-74c7-11e7-9af3-0603417b3b7e.png)

This is related to: https://github.com/fossasia/susi_server/issues/424 and https://github.com/fossasia/susi_skill_data/issues/254

**Comment by saurabhjn76** [comment]
Will work on this
