### ISSUE TITLE
Building  susi_skill set for Computer Networks

### ISSUE THREAD

**Issue by Dhiraj240** [fossasia/susi_skill_cms#1589]
**Actual Behaviour**

Currently the skill based on providing details about basic computer network theory is absent
**Expected Behaviour**

Show details in parts or different categories like :
1.TCP/IP protocols
2.Routers etc.
Hence in a particular tag of Computer Networks set of skills will be developed per week or month.
**Steps to reproduce it**

Using susi_skill documentation

**Would you like to work on the issue?**

Yes

**Comment by Dhiraj240** [comment]
@mariobehling Should i start working.I am codeheat participant.

**Comment by akshatnitd** [comment]
@Dhiraj240 You can start work on it. But you do not need to send a PR for it. Instead, you can log into the website and then make a skill as mentioned in the issue.

**Comment by Dhiraj240** [comment]
@akshatnitd okay , but may i know on which cases i can make PRs in this project.
