### ISSUE TITLE
Enhance skill display on overview page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#159]
The skills on the overview place need to have a clearer design and display info. Please compare to Alexa and follow this approach.

![screenshot from 2017-07-30 00-29-03](https://user-images.githubusercontent.com/1583873/28751529-342189cc-750a-11e7-8633-2dc9a2d83be3.png)

**Comment by meriki** [comment]
Will start working on this.

**Comment by mariobehling** [comment]
@meriki Any update?

**Comment by rishiraj824** [comment]
Will take it up :+1:

**Comment by mariobehling** [comment]
Please check the display of skills on Amazon: https://amazon.com/b?node=13727921011

For now a simple display is sufficient as long as the boxes are there with the content and images.

**Comment by rishiraj824** [comment]
Sure will follow this appraoch.

**Comment by meriki** [comment]
@mariobehling We were learning react and looking for the desired components. Sorry, didn't see the comment. We were thinking of changing the ui a little more and planning for that too so took this much time. We thought of big cards on the first page with the broad topic, knowledge, entertainment, etc, with info regarding what each of them had and then clicking on it which redirects to another page with the skills displayed there(as in alexa). Was just gonna put up the conceptualised diagram now.
