### ISSUE TITLE
Right Skill Column border cut in slider

### ISSUE THREAD

**Issue by tabesin** [fossasia/susi_skill_cms#1591]
**Actual Behaviour**

At my current screen size and FF browser 4 columns of skills are rendered in the scrollbar. However with the right column the right border gets cut. 

**Expected Behaviour**

Distribute the space as to render all four of them within the slider. The slider in the default state should look the same to the left as to the right (mirrored of course).

**Screenshots of the issue**
![sudiskillbug](https://user-images.githubusercontent.com/10114907/45679153-509f9b00-bb38-11e8-9250-8fe389a2c8a8.png)

![sudiskillbug2](https://user-images.githubusercontent.com/10114907/45679490-108ce800-bb39-11e8-97ad-5f5e08eb31ba.png)

**Would you like to work on the issue?**
no.

**Comment by ashutoshsenger** [comment]
I want to work on this issue,please assign it to me.

**Comment by sk9331657** [comment]
@tabesin  I am claiming this.
