### ISSUE TITLE
Botbuilder page cards need left and right margins when screen is squeezed  

### ISSUE THREAD

**Issue by neeraj3029** [fossasia/susi_skill_cms#1617]
**Actual Behaviour**

The elements in botbuilder card touch screen edges when screen size is less.

**Expected Behaviour**

Proper margin and padding is needed.

**Steps to reproduce it**
Open Dashboard and resize the screen.

**Screenshots of the issue**
GIF

![dashb](https://user-images.githubusercontent.com/31539812/46472264-4947e500-c7fa-11e8-8b47-503aa87f5cd1.gif)

**Would you like to work on the issue?**
Yes

**Comment by garvitkhandelwal** [comment]
@AakashMallik anyone working on this?

**Comment by neeraj3029** [comment]
Oh I forgot about this issue, I will be making a PR on this soon.

**Comment by garvitkhandelwal** [comment]
Ok

**Comment by garvitkhandelwal** [comment]
@neeraj3029 any progress?

**Comment by neeraj3029** [comment]
@garvitkhandelwal Sure, you'll get a PR within a week. I believe there is nothing very urgent.
