### ISSUE TITLE
Dropdown menu gets out of the window

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi_skill_cms#1619]
**Actual Behaviour**

Dropdown menu gets out of the window there is no space between dropdown menu and edge of the window .

**Expected Behaviour**

There should be space between the dropdown menu and the window .

**Screenshots of the issue**

![scroll](https://user-images.githubusercontent.com/32234926/46485476-5a541e80-c819-11e8-86fb-c370a99536e6.PNG)

**Would you like to work on the issue?**
Yes

**Comment by tathagat2006** [comment]
@samagragupta can I work on this issue?

**Comment by samagragupta** [comment]
@tathagat2006 Go for it 🚀

**Comment by samagragupta** [comment]
@tathagat2006 you can work on it 🚀

**Comment by tathagat2006** [comment]
Will be on it in a while.

**Comment by tathagat2006** [comment]
@samagragupta working on it.

**Comment by sk9331657** [comment]
@claiming this .

**Comment by samagragupta** [comment]
@sk9331657 What is the progress?
