### ISSUE TITLE
Footer is not responsive

### ISSUE THREAD

**Issue by AdityaSrivast** [fossasia/susi_skill_cms#1622]
**Actual Behaviour**

Currently the footer is not responsive for medium width devices(531-710px)

**Expected Behaviour**

It should be responsive

**Screenshots of the issue**

![screenshot from 2018-10-06 23-16-19](https://user-images.githubusercontent.com/31389740/46575263-e7d96f00-c9cf-11e8-9870-31e006f112f2.png)

**Would you like to work on the issue?**

Yes

**Comment by tathagat2006** [comment]
@AdityaSrivast I would like to work on this issue #1622 .

**Comment by AdityaSrivast** [comment]
@tathagat2006 I am already working on this issue. Try the ones in which *Would you like to work on the issue?* is answered No
