### ISSUE TITLE
Rating chart not properly aligned

### ISSUE THREAD

**Issue by akshi-11** [fossasia/susi_skill_cms#1627]
**Actual Behaviour**

The rating chart shifts left when the screen is narrowed.

**Expected Behaviour**

The rating chart should be properly visible when the screen is narrowed.

**Steps to reproduce it**

Select a skill card from the main page and scroll down to the rating chart. Narrow the screen to see the chart go left.

**Screenshots of the issue**

![2018-10-11](https://user-images.githubusercontent.com/31557923/46822921-6c4e3800-cdaa-11e8-8a10-ca673aa587a6.png)

**Would you like to work on the issue?**

Yes.

**Comment by atharvasharma** [comment]
Can i work on this issue as it is pending from a lot of time.

**Comment by akshi-11** [comment]
The issue is solved, is guess it wasn't closed at that time.
