### ISSUE TITLE
No common helper function/middleware for making API calls

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_skill_cms#1654]
**Actual Behaviour**
* No common helper function/middleware for making API calls, leading to a lot of code duplication.

**Expected Behaviour**
* A function through which all API calls should be made.

**Would you like to work on the issue?**
Yes

**Comment by anshumanv** [comment]
Should we have an `api` folder in `src`?

**Comment by akshatnitd** [comment]
Yes, also we should have a common function that defines how the API calls would be made
