### ISSUE TITLE
Variable names need to be changed

### ISSUE THREAD

**Issue by neeraj3029** [fossasia/susi_skill_cms#1659]
**Actual Behaviour**

A lot of variable names use underscores instead of camel case, because of this **ESLint rejects the commits**.

**Expected Behaviour**

I think it would be better if we use camel case instead of underscores.

**Screenshots of the issue**
Here is a screenshot of ESLint error after a failed commit.

![screenshot 2018-10-30 at 8 28 48 pm](https://user-images.githubusercontent.com/31539812/47728213-e4aa6980-dc83-11e8-9cdd-a6c52f3500b0.png)

**Would you like to work on the issue?**
Yes

**Comment by sk9331657** [comment]
@DNS-404  This can be closed
.
