### ISSUE TITLE
Use fetch instead of JQuery for API calls.

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/susi_skill_cms#1668]
**Actual Behaviour**

We are using JQuery as our Ajax library that is causing a mess in the code base.

**Expected Behaviour**

We should use fetch, which is a much cleaner and simple libarary.

**Would you like to work on the issue?**
Yes please. @Akshat-Jain @akshatnitd I need your suggestion on this. The current codebase is a mess, this would be a small step towards cleaning it up.

**Comment by anshumanv** [comment]
Ah thanks for posting this, I think I'll be using axios from - https://github.com/fossasia/susi_skill_cms/issues/1653

We would need a lot of refactoring then so please help with that, I'll send a PR once it's merged in chat.

**Comment by AakashMallik** [comment]
@akshatnitd Sir, I understand your concern. I actually wanted to discuss this with you. Could the mentors and intereted contributors have a hangout meetup so that everyone could be on the same page about improvements and progress?
