### ISSUE TITLE
Follow position of logo and height/design of top bar of web chat

### ISSUE THREAD

**Issue by hpdang** [fossasia/susi_skill_cms#167]
The height, position, size of the logo is not following the webchat. Please adhere to it.

.ico is also not same as web chat. Please adhere to it!

**Comment by uday96** [comment]
Will change it :+1:

**Comment by uday96** [comment]
@hpdang @mariobehling  asked for the logo to be positioned on left in https://github.com/fossasia/susi_skill_cms/issues/156#issue-246550172 . Should I align it to center or leave it at left?

**Comment by mariobehling** [comment]
@uday96 Leave it on the left and follow the design of the Overview Page: http://chat.susi.ai/overview

Please also ensure the top bar behaves in the same way and the right scroll bar is acting in the same way.
