### ISSUE TITLE
Add a utility file for ajax calls

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/susi_skill_cms#1690]
**Actual Behaviour**

We don't have a helper file to make ajax calls.

**Expected Behaviour**

A single interface for making ajax calls should be introduced in order to encourage uniformity and remove jquery dependency. 

**Would you like to work on the issue?**

Yes

**Comment by anshumanv** [comment]
This will be done as a part of https://github.com/fossasia/susi_skill_cms/issues/1653

No need to do this separately. :smile:

**Comment by AakashMallik** [comment]
Okay
