### ISSUE TITLE
Post Login screen is always in loading state

### ISSUE THREAD

**Issue by AdityaSrivast** [fossasia/susi_skill_cms#1693]
**Actual Behaviour**

Currently the post login screen is always in loading state and does not render the elements

**Expected Behaviour**

The screen should not be always in loading state and the components should be rendered.

**Steps to reproduce it**

Login to https://skills.susi.ai

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/31389740/49072897-447e3b00-f257-11e8-97aa-ecd61de87738.png)

**Would you like to work on the issue?**

Yes

**Comment by AakashMallik** [comment]
@AdityaSrivast There is a PR and an issue already open regrading this. Do check the list of issues before opening a new one. https://github.com/fossasia/susi_skill_cms/issues/1666
