### ISSUE TITLE
Create Skill Bot should redirect to /botbuilder/botwizard

### ISSUE THREAD

**Issue by AdityaSrivast** [fossasia/susi_skill_cms#1696]
**Actual Behaviour**

Currently *Create Skill bot* on the root page redirects to /botbuilder.

**Expected Behaviour**

It should redirect to /botbuilder/botwizard, analogous to *Create a Skill*, which redirects to /skillCreator

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/31389740/49271134-64e60980-f492-11e8-8b19-3a76aac4dcf7.png)

**Would you like to work on the issue?**

Yes.

**Comment by anshumanv** [comment]
This is intentional and therefore closing it, thanks.
