### ISSUE TITLE
botbuilder: the buttons in delete bot modal are inconsistent

### ISSUE THREAD

**Issue by AdityaSrivast** [fossasia/susi_skill_cms#1697]
**Actual Behaviour**

Currently the delete button has pink background and looks inconsistent in the app.

**Expected Behaviour**

It should be consistent.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/31389740/49302594-8a543100-f4ed-11e8-8b04-24d9838a298b.png)

**Would you like to work on the issue?**

Yes.

**Comment by anshumanv** [comment]
Thanks for this, please make it danger red.
