### ISSUE TITLE
List all the users along with their user roles

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/susi_skill_cms#170]
**Expected Behaviour**
Admins should have access to list of all the users from where they can also change user role.

**Would you like to work on the issue?**
Yes

**Comment by DravitLochan** [comment]
@mariobehling By mistake I added "fixes #170" in #172 . Please re-open this issue. I will add details about when user signed up, last login details and IP of last login.

**Comment by mariobehling** [comment]
Please also follow up here: https://github.com/fossasia/susi_skill_cms/issues/186

**Comment by akshatnitd** [comment]
Also done, hence closing.
