### ISSUE TITLE
Fix Dropdown menu structure and views across apps and pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#173]
Related to: https://github.com/fossasia/chat.susi.ai/issues/657

**Not logged in users:**
About -> Overview
Chat -> /chat app
Skills -> / skills app
Settings -> /settings
Login -> login

**Logged in users:**
About -> Overview
Chat -> /chat app
Skills -> / skills app
Settings -> /settings
[Themes -> theme popup (only in chat app)]
Logout -> logout

* Add icons to all menu items
* Don't show "signup" on menu. The link to signup on the login page is sufficient.
* On chat app direct settings to chat app settings
* On skills cms direct settings link to skills settings
* Ensure the dropdown menu works on the same way on chat pages overview etc.

**Comment by madhavrathi** [comment]
Will do this.

**Comment by mariobehling** [comment]
@madhavrathi Looks like you simply copied the code from the chat. The about link needs to direct to chat.susi.ai/overview. Please fix it.

**Comment by madhavrathi** [comment]
@mariobehling I have not copied the code. I am sorry you feel this way but I have already asked this question where to redirect on tapping about. There were no answers from the mentioned people so I redirected it /overview. Again I am sorry if you feel this way. I will send a PR right now to fix this.
