### ISSUE TITLE
Make browser skills side bar compatible with mobile/low dimension screen

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_skill_cms#1734]
**Actual Behaviour**

On decreasing the width, the sidebar of browseskill disappears.

**Expected Behaviour**

Display a mobile menu toggle(hamburger type) which lets the user view the sidebar on click

**Would you like to work on the issue?**

Yes

**Comment by sk9331657** [comment]
@fragm3  Can I work on this??

**Comment by fragm3** [comment]
@sk9331657 Hey, I have started working on it.
