### ISSUE TITLE
render to login page when create a skill without logged in

### ISSUE THREAD

**Issue by avsingh999** [fossasia/susi_skill_cms#1736]
**Actual Behaviour**
when a user is not logged in and then click on create a skill it should be showing a login page for login

**Expected Behaviour**

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

**Comment by anshumanv** [comment]
There's no login page, it's just a dialog which is accessible from the Topbar, hence closing this.

Also, please fill the issue template properly.
