### ISSUE TITLE
Skill Creator component is not aligned properly in mobile view

### ISSUE THREAD

**Issue by plxity** [fossasia/susi_skill_cms#1738]
**Actual Behaviour**

![capture](https://user-images.githubusercontent.com/28510494/50382871-c0409b80-06ce-11e9-85b5-03a24302e7bd.PNG)

**Expected Behaviour**

Form elements should be properly aligned.

**Steps to reproduce it**

1) Visit https://skills.susi.ai/skillCreator

**Would you like to work on the issue?**

Yes, I would like to work on this.

**Comment by garvitkhandelwal** [comment]
Any progress?
