### ISSUE TITLE
SKILLS BUTTON 

### ISSUE THREAD

**Issue by pg07codes** [fossasia/susi_skill_cms#1745]
![image](https://user-images.githubusercontent.com/34238240/48472317-0b3bd900-e81c-11e8-8caa-95133747cc4e.png)
Problem:
- On clicking the button under Staff Picks, it just toggles it position to the left of the window.  

Possible Solution:  

-  As there is no content to scroll-by , the button should be disabled by default.

**Comment by sk9331657** [comment]
@pg07codes  I can't figure out this issue. Can you post a gif about this issue??
