### ISSUE TITLE
Change SkillScrollCardGrid design

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_skill_cms#1764]
**Actual Behaviour**

Improve the design of SkillScrollCardGrid

**Expected Behaviour**

Make it something like:

<img width="313" alt="screenshot 2019-01-01 at 7 06 51 pm" src="https://user-images.githubusercontent.com/18073126/50573378-b9b1d280-0df8-11e9-9936-f4085a68edfb.png">

**Would you like to work on the issue?**

Yes

**Comment by sweezy793** [comment]
Can you please tell in which directory this component belongs to?

**Comment by fragm3** [comment]
@sweezy793 I will be working on this, belongs to **SkillScrollCardGrid** in `src/components`

**Comment by fragm3** [comment]
Will proceed with this once https://github.com/fossasia/susi_skill_cms/pull/1787 is merged
