### ISSUE TITLE
Follow web chat and use same icons in dropdown

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#178]
![screenshot from 2017-08-02 14-21-26](https://user-images.githubusercontent.com/1583873/28873836-8c23ebc4-778f-11e7-9a33-514c1f60ae6c.png)

Please implement and use the same icons.

**Comment by rishiraj824** [comment]
will do this

**Comment by madhavrathi** [comment]
@rishiraj824 @dynamitechetan @saurabhjn76  I guess this issue can be closed now.
