### ISSUE TITLE
Skill heading references wrong skill

### ISSUE THREAD

**Issue by tabesin** [fossasia/susi_skill_cms#181]
**Actual Behaviour**
1) Go to http://skills.susi.ai/
2) select e.g. Github.
3) page shows Github skill but header says Wikipedia

**Expected Behaviour**

On a Github skill page, header says github skill.

As a result I also wonder if changes would be committed to the right skill.

**Screenshots of the issue**

![bildschirmfoto vom 2017-08-03 00-04-39](https://user-images.githubusercontent.com/10114907/28897087-6da0d068-77df-11e7-9f70-0ff3fcaa14bb.png)

**Comment by dynamitechetan** [comment]
This has been fixed. The Wikipedia card was just a placeholder and was showing dummy values.
It is removed now.

**Comment by saurabhjn76** [comment]
Placeholder card is removed, now showing correct information
