### ISSUE TITLE
Signup snackbar message is incomplete 

### ISSUE THREAD

**Issue by sweezy793** [fossasia/susi_skill_cms#1810]
**Actual Behaviour**

After Signing up the snackbar message is incomplete, it shows "You successfully signed-up! An email with a verification link was sent to your"

**Expected Behaviour**

Message should be "You successfully signed-up! An email with a verification link was sent to your address"

**Screenshots of the issue**

![screenshot from 2019-01-13 21-37-43](https://user-images.githubusercontent.com/23583306/51087838-31c7b300-177e-11e9-96be-06f221e4d4ee.png)

**Would you like to work on the issue?**

Yes

**Comment by AakashMallik** [comment]
@sweezy793 Good catch. Try following what we have done in Susi chat. This will keep the apps consistent as far as UX in concerned.

**Comment by sweezy793** [comment]
@AakashMallik I will keep that in mind :)

**Comment by sweezy793** [comment]
@AakashMallik I checked how Sign up was done in Susi chat but there are a lot of changes between this and Susi chat. I tried changing the snackbar message a little bit and now snackbar shows complete message, should I stick with this?

**Comment by sweezy793** [comment]
@AakashMallik I tried Susi chat way and it works but the sign up popup stays up until you manually close it by clicking the X in pop up. I think snackbar will work out better as it will automatically disappear, but if I do the snackbar way I would have to manually assign a constant with the success message, it doesn't show the complete message from payload. 

![screenshot from 2019-01-14 01-13-14](https://user-images.githubusercontent.com/23583306/51089834-9e9c7680-1799-11e9-965b-1bd62eeb6e29.png)

**Comment by anshumanv** [comment]
+1 for the signup message persistence, the question is where will it look good 🤔

**Comment by sweezy793** [comment]
@anshumanv does it look good in the screenshot I attached?

**Comment by sweezy793** [comment]
@AakashMallik what  do you think I should do ?

**Comment by AakashMallik** [comment]
@sweezy793 I am against server message tampering so I think the susi chat thing would be the best way to work this out.

**Comment by sweezy793** [comment]
@AakashMallik then I will get at it :+1:
