### ISSUE TITLE
Error in logging in susi skill cms

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/susi_skill_cms#1819]
**Actual Behaviour**
After logging in, the user email id is not displayed on top right corner and it again gives the option to log in.
**Expected Behaviour**
User login should work as expected.
**Screenshots of the issue**
![screenshot 2019-01-15 at 12 49 20 pm](https://user-images.githubusercontent.com/31013104/51164782-14046600-18c4-11e9-911b-b29c1eafb677.png)

**Comment by AakashMallik** [comment]
@harsh-jindal I have a PR open that resolves this issue...  u may close this issue...

**Comment by harsh-jindal** [comment]
Okay
