### ISSUE TITLE
Make use of snackbar actions and reducers in the requried components

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/susi_skill_cms#1821]
**Actual Behaviour**

The components are currently using the functions that are being passed by the parent component

**Expected Behaviour**

Make use of actions created in https://github.com/fossasia/susi_skill_cms/issues/1820 to dispatch changes to snackbar variables present in global store.

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
Duplicate of https://github.com/fossasia/susi_skill_cms/issues/1808
