### ISSUE TITLE
Create global Dialog state, actions and reducers for login/signup/forgot password

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/susi_skill_cms#1822]
**Actual Behaviour**

Currently these variables are stored as state variables of parent component.

**Expected Behaviour**

The variables must be stored in the redux store and actions must be created to maniuplate them

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
Duplicate of https://github.com/fossasia/susi_skill_cms/issues/1815
