### ISSUE TITLE
Fix Bug in Login Page

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/susi_skill_cms#1827]
**Actual Behaviour**
On incorrect login the message displayed is "Login Failed.Try Again." and the email Id is not cleared. 
**Expected Behaviour**
On incorrect login the message displayed is "Invalid details. Please check the Email ID - Password combination." and the email Id should be cleared. 
**Screenshots of the issue**
![screenshot 2019-01-16 at 12 21 43 am](https://user-images.githubusercontent.com/31013104/51202449-c66c1580-1924-11e9-8249-bd3ab0824fe7.png)

**Would you like to work on the issue?**
Yes

**Comment by AakashMallik** [comment]
@harsh-jindal  Not sure if this is needed.
