### ISSUE TITLE
Tutorial: Document what is a model and what is a group

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#183]
New users will not know what is a model and a group. Please document this in the tutorial.

**Comment by dynamitechetan** [comment]
Okay. Should we also include a link to the tutorial in the menu item?

**Comment by dynamitechetan** [comment]
https://github.com/fossasia/susi_skill_data/pull/264
Updated the tutorial at skill_skill_data

**Comment by rishiraj824** [comment]
@saurabhjn76 this can be closed

**Comment by jajodiaraghav** [comment]
Is there anything else required here, or can this be closed?

**Comment by codejockie** [comment]
What does the documentation entail?

**Comment by akshatnitd** [comment]
It has been done. Hence, closing.
