### ISSUE TITLE
For Admin Users show menu item "Admin" 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#186]
Users List was implemented in the dropdown menu for all users. It should not be there.

Please implement a menu item "Admin" below the settings item. Only show this point for admin users! Do not show this menu item for anonymous or logged in users.

On the page on the route `/admin` show tabs for `users` and `permissions` similar to this one (but using the design of the skills cms).

**Comment by DravitLochan** [comment]
Will start working on it :+1:

**Comment by DravitLochan** [comment]
@mariobehling Please suggest any possible changes.
![admin](https://user-images.githubusercontent.com/14837478/29206119-2d155404-7e9e-11e7-80ac-4109bc9ca364.png)

**Comment by mariobehling** [comment]
I am having difficulties describing each and every single improvement needed. Please follow common design thinking

* Don't use full width for everything
* We don't have an admin panel, there should be a dashboard
* The users table should not be attached to the tab itself

**Comment by mariobehling** [comment]
Do check out the Open Event admin section. I have the feeling you never checked it out.

**Comment by DravitLochan** [comment]
Since all the users are being fetched at once, It takes time and was getting difficult to manage. https://github.com/fossasia/susi_server/pull/491 will change the end point to /getUsers and now only 50 users will be fetched at a time making. To implement this, I will add buttons in the footer. (A similar approach to how github manages many issues of a project)

**Comment by mariobehling** [comment]
Please follow up until all fields and tabs have complete data and functionality.

**Comment by akshatnitd** [comment]
It has been done. Hence, closing.
