### ISSUE TITLE
Integrate Redux for SkillCreator and Child component

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_skill_cms#1867]
**Actual Behaviour**

After #1866

**Expected Behaviour**

Integrate Redux for SkillCreator and Child component

**Would you like to work on the issue?**

Yes

**Comment by harsh-jindal** [comment]
@fragm3 I have created a issue https://github.com/fossasia/susi_skill_cms/issues/1974 for integrating redux in skillviews. Can I go ahead?

**Comment by fragm3** [comment]
@harsh-jindal Do you want to specifically work on the skillViews part?

**Comment by harsh-jindal** [comment]
@fragm3 Yes. If we change everything at once it's difficult to review.

**Comment by fragm3** [comment]
Will proceed with this, once https://github.com/fossasia/susi_skill_cms/pull/1975 is merged.
