### ISSUE TITLE
Skill image icons disappear after clicking the search arrow button

### ISSUE THREAD

**Issue by isuruAb** [fossasia/susi_skill_cms#188]
**Actual Behaviour**

Skill image icons disappear after clicking the search arrow button

**Expected Behaviour**

Icons should show as it is after clicking the search button

**Screenshots of the issue**

<img width="1260" alt="screen shot 2017-08-05 at 9 10 56 pm" src="https://user-images.githubusercontent.com/7692626/29021637-ce9ab828-7b83-11e7-9e9a-44eb04a47e6f.png">

**Would you like to work on the issue?**

anyone can get this

**Comment by saurabhjn76** [comment]
It has been fixed in #184
