### ISSUE TITLE
Fix console errors for susi skills

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_skill_cms#1882]
**Actual Behaviour**

Console errors present

**Expected Behaviour**

Fix the console errors shown in screenshots

**Screenshots of the issue**

<img width="1440" alt="screenshot 2019-01-24 at 1 37 18 pm" src="https://user-images.githubusercontent.com/18073126/51663638-49eccd00-1fdd-11e9-9ad9-81c7f022295f.png">
<img width="1440" alt="screenshot 2019-01-24 at 1 37 31 pm" src="https://user-images.githubusercontent.com/18073126/51663639-4a856380-1fdd-11e9-95bb-1186897d475a.png">

**Would you like to work on the issue?**

Yes

**Comment by AakashMallik** [comment]
This will lead to a lot of changes at once. How about we split the issue into smaller chunks. Maybe target a single type of error per issue? Ur call.

**Comment by fragm3** [comment]
@AakashMallik I think some of these are simple, i'll look into this. If they are complex we will split

**Comment by AakashMallik** [comment]
Sure...

**Comment by fragm3** [comment]
@AakashMallik I am leaving this: https://github.com/fossasia/chat.susi.ai/pull/1980, once it gets merged there. You can create same for skills susi

**Comment by AakashMallik** [comment]
@fragm3 DOMnesting error is not there in CMS. I'll see if any error pops up after ur merge, I'll pick it up.

**Comment by fragm3** [comment]
@AakashMallik just saw it today, ill share screenshot if it comes up
