### ISSUE TITLE
Show skills on the home page in descending order of rating 

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/susi_skill_cms#1893]
**Actual Behaviour**
Skills are shown in any order of rating.

**Expected Behaviour**
It would be better to show skills in decreasing order of rating.

**Screenshots of the issue**
![screenshot 2019-01-25 at 11 02 44 pm](https://user-images.githubusercontent.com/31013104/51762302-5b28fd00-20f5-11e9-82ac-7362f3102d2d.png)

**Would you like to work on the issue?**
Yes

**Comment by AakashMallik** [comment]
Not a good idea for obvious reasons

**Comment by AakashMallik** [comment]
But, you could set up an option for the user to use this functionality IF and only IF he wants to use it.

**Comment by harsh-jindal** [comment]
@AakashMallik I guess we could order the skill's based on the heading then. I mean for the newest skills sorted by last created, for most feedback sorted by feedback count and so on. Because showing a skill with 0 rating under most used skill or highest rated on front page doesn't look good.

**Comment by AakashMallik** [comment]
> @AakashMallik I guess we could order the skill's based on the heading then. I mean for the newest skills sorted by last created, for most feedback sorted by feedback count and so on. Because showing a skill with 0 rating under most used skill or highest rated on front page doesn't look good.

Try a metric that is a combination of ( how high the rating is ) and ( how many people have actually rated it ). May be a simple product of the two would be a good metric to start with.

**Comment by harsh-jindal** [comment]
@AakashMallik That sounds good, will try to implement it in that way.
