### ISSUE TITLE
Shift from CSS to styled-components

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/susi_skill_cms#1904]
Actual Behaviour

We are making use of CSS to style the components as of now.

Expected Behaviour

Make use of more modular and reliable styled-components

Would you like to work on the issue?

Yes

Note: As this is not a pressing issue, I'll work on it after the redux integration has been done.

**Comment by anshumanv** [comment]
Probably we'll get rid of MUI too once we have our own CSS.

**Comment by AakashMallik** [comment]
@anshumanv Yeah, that would be fun

**Comment by harsh-jindal** [comment]
@AakashMallik I think this issue can be closed as we are migrating from CSS to styled-components component by component.
