### ISSUE TITLE
Reuse staticAppBar by creating a layout component

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/susi_skill_cms#1905]
**Actual Behaviour**

The StaticAppBar is being re-rendered for every route

**Expected Behaviour**

This is undesirable behavior as the staticAppBar can be reused as a parent component and the routes being the children.

**Would you like to work on the issue?**

Yes

**Comment by harsh-jindal** [comment]
@AakashMallik This can be done once we migrate to mono repo.
