### ISSUE TITLE
Password Field gives length undefined error on signup

### ISSUE THREAD

**Issue by modestlearner** [fossasia/susi_skill_cms#1913]
**Actual Behaviour**

**Expected Behaviour**

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

**Comment by AakashMallik** [comment]
@modestlearner A PR has already been opened for this https://github.com/fossasia/susi_skill_cms/pull/1907 You may close this issue.
