### ISSUE TITLE
Login modal not opening on Protected route

### ISSUE THREAD

**Issue by plxity** [fossasia/susi_skill_cms#1914]
**Actual Behaviour**

Login modal is not opening when you visit protected route like https://skills.susi.ai/botbuilder 

**Expected Behaviour**

Login Modal should open.
**Steps to reproduce it**

1) Visit route like https://skills.susi.ai/botbuilder without logging in to your account.
2) Click on login option in the navigation bar,

**Would you like to work on the issue?**
Yes, I would like to work on this.

**Comment by AakashMallik** [comment]
Actually, this issue would be redundant as @fragm3 has an issue passing the actions he created for Dialogs and snackbar https://github.com/fossasia/susi_skill_cms/issues/1816. Exactly the reason why I closed my issue https://github.com/fossasia/susi_skill_cms/issues/1798 a few days back. :innocent:

**Comment by plxity** [comment]
@AakashMallik Oh Okay, No issues. :)
