### ISSUE TITLE
Remove jQuery ajax dependency for SkillVersion

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_skill_cms#1920]
**Actual Behaviour**

API is hit using jQuery ajax

**Expected Behaviour**

Use helper API method instead

**Would you like to work on the issue?**

Yes

**Comment by meetzaveri** [comment]
Hey, I saw that everywhere you are using jQuery's ajax method to call API. Instead the modern way to execute API is using ES6 fetch API or using third party library like axios.

I would like to refactor if you came up with solution already.

**Comment by fragm3** [comment]
@meetzaveri We are using axios now, will be creating a PR today

**Comment by meetzaveri** [comment]
Okay @fragm3 ! Great! Is there any other module containing jQuery ajax method ? I am looking to contribute in that area

**Comment by fragm3** [comment]
@meetzaveri Admin components
