### ISSUE TITLE
the footer is not fixed at the bottom for pages with a small height.

### ISSUE THREAD

**Issue by ArexJambusarwala** [fossasia/susi_skill_cms#1932]
**Actual Behaviour**

The footer is not fixed at the bottom for pages with a small height.

**Expected Behaviour**

The footer should be fixed at the bottom.

**Steps to reproduce it**

Example page: https://skills.susi.ai/Utilities/test/en/feedbacks

**Screenshots of the issue**

![issue9](https://user-images.githubusercontent.com/35253743/52839277-88c4fd00-311b-11e9-9f7b-73475beaa6d7.png)

**Would you like to work on the issue?**

Yes

**Comment by modestlearner** [comment]
Can I take this issue if no one is doing it???
