### ISSUE TITLE
Recaptcha not working at https://skills.susi.ai/ in sign up

### ISSUE THREAD

**Issue by Akshay090** [fossasia/susi_skill_cms#1936]
**Actual Behaviour**

Error for site owner Invalid domain for site key

**Expected Behaviour**

recaptcha not functioning

**Steps to reproduce it**

not able to sign up from https://skills.susi.ai/

**LogCat for the issue**

**Screenshots of the issue**

![susi error](https://user-images.githubusercontent.com/28626499/52875119-885b4f00-3179-11e9-87b3-d3b467b5db64.png)

**Would you like to work on the issue?**

yes, but i guess the admin just have to generate a new key

**Comment by AakashMallik** [comment]
@Akshay090 How do you plan to fix this?

**Comment by sarthak247** [comment]
@AakashMallik , I was also trying to signup for susi skills and encountered the same issue. I did some research and it seems like the reCAPTCHA has broken. If no one is working on this, can I work on this?

**Comment by Akshay090** [comment]
@sarthak247 you can take it i dont plan to work on it

**Comment by fragm3** [comment]
Fixed.
