### ISSUE TITLE
Replicate Settings of Chat app

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#195]
The chat app settings can be copied to be used in this app. Please do so.

**Comment by saurabhjn76** [comment]
I would like to work on it.

**Comment by saurabhjn76** [comment]
@mariobehling, Do we require any other settings apart from theme ?
![image](https://user-images.githubusercontent.com/9781788/29239733-935f78be-7f72-11e7-9b5c-e844e2a1331c.png)
