### ISSUE TITLE
Place staff skills in slider in mobile view

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/susi_skill_cms#1950]
**Actual Behaviour**
In mobile view the staff skills are shown one below the other.

**Expected Behaviour**
Place staff skills in slider in mobile view

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**
![Screenshot 2019-04-04 at 11 59 10 AM](https://user-images.githubusercontent.com/31013104/55534143-21fea180-56d1-11e9-9779-8c35e21f9e13.png)

**Would you like to work on the issue?**
I am working on it.

**Comment by kshitijk83** [comment]
i don't know what's wrong, every thing seems to be right? but the right button always have display:none and scrolling-wrapper class named div(only for staff picks not for other's) doesn't have style named as grid list, can you have the idea why is this happening? @harsh-jindal

**Comment by harsh-jindal** [comment]
@kshitijk83 Try reducing the browser size at one point the 2 cards will be one line and the other in next line. Right button display:none is done when number of total cards if less that what can be displayed on screen. class named div(only for staff picks not for other's) doesn't have style named as grid list : Yes this I noticed as some unexpected behaviour as all divs were given the same styles.

**Comment by kshitijk83** [comment]
do u have any idea why this is happening? why styles aren't applied?

**Comment by harsh-jindal** [comment]
@kshitijk83 Nope.Will have to take a deeper look at it.

**Comment by kshitijk83** [comment]
i think i have resolved this issue, but i while PR i i can't find pull request number for deployment in surge

**Comment by AakashMallik** [comment]
> i think i have resolved this issue, but i while PR i i can't find pull request number for deployment in surge
> @harsh-jindal

Submit the PR, the number shall appear after that. Then edit the description accordingly.

**Comment by kshitijk83** [comment]
drag and drop is not working in ubuntu how can i upload a screenshot for showing the change?

**Comment by kshitijk83** [comment]
@AakashMallik  @harsh-jindal please check the PR

**Comment by kshitijk83** [comment]
@AakashMallik @harsh-jindal i think the issue is resolved can you please check the PR
