### ISSUE TITLE
Upgrade to newer React version

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_skill_cms#1963]
**Actual Behaviour**

Currently running an older version of React

**Expected Behaviour**

Upgrade to newer react version 16.4

**Would you like to work on the issue?**

Yes

**Comment by harsh-jindal** [comment]
@fragm3 Are you working on this? For Integration of Styled components I first need to upgrade react version.

**Comment by fragm3** [comment]
@harsh-jindal you can take this up. If you want to specifically work on styled components, you can branch out from my PR#2079. We would use a common approach to handle and manage our styling.

**Comment by harsh-jindal** [comment]
@fragm3 Sure I'll take this up.But I'm not sure how to branch out from PRhttps://github.com/fossasia/chat.susi.ai/pull/2079 
Please guide on that

**Comment by fragm3** [comment]
@harsh-jindal It will probably be merged by today. You can branch out by `fork`, then `clone`  then `git checkout -b` on my branch.
