### ISSUE TITLE
Compress image before uploading to server

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/susi_skill_cms#1985]
**Actual Behaviour**
Currently the user can upload image of any size.

**Expected Behaviour**
Compress the image before uploading to server. For this I'll use browser-image-compression (link: https://www.npmjs.com/package/browser-image-compression)

**Would you like to work on the issue?**
Yes

**Comment by harsh-jindal** [comment]
@akshatnitd Shall i go ahead or use some other lib?

**Comment by fragm3** [comment]
@harsh-jindal This would be done on the server side. Once the user uploads the image, the server compresses it.

**Comment by harsh-jindal** [comment]
@fragm3 Okay, I'll open a issue in susi server repo.
