### ISSUE TITLE
Upgrade material UI in StaticAppBar

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_skill_cms#1998]
**Actual Behaviour**

Old version present, following up on PR: https://github.com/fossasia/susi_skill_cms/pull/1982

**Expected Behaviour**

Upgrade Material UI version

**Would you like to work on the issue?**

Yes

**Comment by harsh-jindal** [comment]
@fragm3 I am working on the Auth Component https://github.com/fossasia/susi_skill_cms/issues/1976
