### ISSUE TITLE
Private APIs as hidden skills

### ISSUE THREAD

**Issue by Fluepke** [fossasia/susi_skill_cms#2]
APIs are an important source of information for the susi.ai project.
Unfortunately many APIs are not open and require an API key.

Thus, here are some thoughts, how we could deal with this issue:
1.  Convince everybody to offer open APIs to support FOSS 😀 (Ok, I know. That's seems rather unlikely)
2. A *key server* at which the developers register using their Facebook, Twitter, Google, whatever account. Via these accounts the server could automatically fetch API keys, which could be supplied to the local development setup via a command line tool and one single API key.
3. The *default way* (most projects, I have seen do it this way): Use a local config file for API keys that will be `git ignored`. This has the disadvantage that every developer needs to acquire API keys for all the services. Some API keys for German public transportation services even require you to ask in German for an API key.
4. Combing `2` and `3`: A command line tool that can automate the process of acquiring API keys (running only locally)
5. Find a way to offer `hidden skills` and to share them with other users.

I'd prefer the last option, even though we might offer a general approach to other OSS projects with one of the other ideas.

**Comment by Orbiter** [comment]
A slightly different idea would be, to provide API shortlinks inside of susi where a user is able to store the actual API url with the embedded key but then get a shortlink to be used within the skill. 

To do that, we would need a kind of 'shortlink registration zone' for each user.

Alternatively, we can provide a private key store for each user and the user then adds the key to the private key to the skill.

The advantage for both methods is, that everyone can read and understand the skill, but does not see the API key.
