### ISSUE TITLE
All tiles in same size

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#208]
Tiles on the overview page currently have different sizes. Please ensure all tiles have the same size.

![screenshot from 2017-08-12 00-46-05](https://user-images.githubusercontent.com/1583873/29234514-c7bdf976-7ef7-11e7-8a14-6ef9f22b96e6.png)

**Comment by madhavrathi** [comment]
@mariobehling this issue is solved in this PR : https://github.com/fossasia/susi_skill_cms/pull/206
Please review.
Thanks

**Comment by madhavrathi** [comment]
@dynamitechetan @saurabhjn76 @mariobehling Please close this issue. This has been solved by  PR : #206
