### ISSUE TITLE
Make frontend for versioning

### ISSUE THREAD

**Issue by dynamitechetan** [fossasia/susi_skill_cms#212]
Show a list of commits and commit message on the skill page. On clicking on the commit the user can see the file at that commit ID. Then there must be a button so that admin can roll back to a commit id.
**API to get commits of a skill:** http://api.susi.ai/cms/getSkillHistory.json?model=general&group=Knowledge&language=en&skill=bitcoin
**API to get skill at a commit ID:** http://api.susi.ai/cms/getFileAtCommitID.json?model=general&group=Knowledge&language=en&skill=bitcoin&commitID=108631fdbd0b463c811bfb9ff3ff7ee1785c55fd

**Comment by uday96** [comment]
Will work on this :+1:

**Comment by dynamitechetan** [comment]
Thanks.
