### ISSUE TITLE
Sort Skills in ascending order 

### ISSUE THREAD

**Issue by isuruAb** [fossasia/susi_skill_cms#226]
**Actual Behaviour**

since skills are not sorted users can't find skills quickly

**Expected Behaviour**

Skills should be sorted in ascending order 

**Screenshots of the issue**

<img width="1244" alt="screen shot 2017-08-16 at 12 48 06 pm" src="https://user-images.githubusercontent.com/7692626/29352205-7f6e9ede-8283-11e7-8083-f5e70d64b146.png">

**Would you like to work on the issue?**

yes

**Comment by DravitLochan** [comment]
shouldn't this go on server so that each client can use the results from server? should I implement an API which does this? I'd like to work on it.

**Comment by isuruAb** [comment]
@DravitLochan  that would be better if you can implement it in server. I wll close this issue and my PR.
