### ISSUE TITLE
Make the app responsive

### ISSUE THREAD

**Issue by uday96** [fossasia/susi_skill_cms#230]
**Actual Behaviour**

The app shows horizontal scroll in mobile view for pages like
 - skillPage
 - createSkillPage

**Expected Behaviour**

Make the app responsive and avoid horizontal scrolls

**Would you like to work on the issue?**

@saurabhjn76 Please take a look at this

**Comment by saurabhjn76** [comment]
@uday96 thanks, I will fix this up.
