### ISSUE TITLE
Can't access routes directly

### ISSUE THREAD

**Issue by isuruAb** [fossasia/susi_skill_cms#231]
**Actual Behaviour**

When user try to access this URL http://localhost:3000/skillPage it gives following error. and gives nothing. 
<img width="486" alt="screen shot 2017-08-17 at 4 51 18 pm" src="https://user-images.githubusercontent.com/7692626/29410156-fd4f0a34-836c-11e7-969f-fef6a1841221.png">

**Expected Behaviour**

If the router does not give anything it should be redirected to the 404 page.

Suggestion: If we can makes routes like /skillPage/:skillName: for skills 
and edit page
/skillPage/:skillName:/editSkill

This would be good. then users can share  Skill URLs also.

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

<img width="1163" alt="screen shot 2017-08-17 at 5 22 53 pm" src="https://user-images.githubusercontent.com/7692626/29411007-c0a31086-8370-11e7-8dd5-b4bdb58b9ec1.png">

**Would you like to work on the issue?**

yes

**Comment by mariobehling** [comment]
Instead of having those URLs, each skill, version, skill editor of a skill should have its own URL - just like Wikipedia.

**Comment by uday96** [comment]
Will implement for version, history and rollback :+1:
