### ISSUE TITLE
Avoid scroll bars in skill editors

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#262]
Skill editors of existing skills show a scroll bar. Please implement automatic line breaks and avoid scroll bars similar to Etherpads.

![screenshot from 2017-08-22 14-07-16](https://user-images.githubusercontent.com/1583873/29564766-711d668e-8743-11e7-902a-708d46d541f5.png)

**Comment by dynamitechetan** [comment]
Working on it

**Comment by isuruAb** [comment]
@mariobehling  this issue can be closed
