### ISSUE TITLE
Clicking on "Versions" does not bring up the usual editing window and no save button

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#264]
If a user wants to revert to an earlier versions and clicks on a version, there is not the usual top bar and the bottom save button is missing. Please implement as follows:

1. Add a new "notifications area" on top and take out the space in front of colon. Show as in this example:
```
You are currently editing an older version of the skill: distance
Author: [add author here]   Commit ID: 108631fdbd0b463c811bfb9ff3ff7ee1785c55fd
Revision as of Thu Aug 10 00:18:14 CEST 2017
```
2. Ensure you are using the same skill editor as on the "edit skill page" and
* include the top bar.
![screenshot from 2017-08-22 14-22-02](https://user-images.githubusercontent.com/1583873/29565223-56bef7c4-8745-11e7-8e48-13a22023f580.png)
* include the bottom bar
![screenshot from 2017-08-22 14-22-46](https://user-images.githubusercontent.com/1583873/29565241-6f0cbeec-8745-11e7-9612-88e03e52ecae.png)
* add a "cancel" button, that cancels the current changes and returns the user to the skill page

**Comment by rishiraj824** [comment]
will do this
