### ISSUE TITLE
Compare selected versions and undo not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#265]
The compare selected button is not working in most cases or takes a super long time to load. If the compare screen is available, the "Undo" button does not load a page.

![screenshot from 2017-08-22 14-24-26](https://user-images.githubusercontent.com/1583873/29565317-be061016-8745-11e7-9b47-d386cb9d02cc.png)

It just stays loading forever in most cases.
![screenshot from 2017-08-22 14-25-43](https://user-images.githubusercontent.com/1583873/29565331-ce69595e-8745-11e7-9db8-f86be154910c.png)

**Comment by uday96** [comment]
Will work on this
