### ISSUE TITLE
Clean up skill history component

### ISSUE THREAD

**Issue by uday96** [fossasia/susi_skill_cms#291]
**Actual Behaviour**

After https://github.com/fossasia/susi_skill_cms/pull/276, the functionality in skill history has been routed to edit skill for seeing the content of a single revision. Clean up that code from skill history component

**Would you like to work on the issue?**

Yes

**Comment by rishiraj824** [comment]
@saurabhjn76 this can be closed now.

**Comment by uday96** [comment]
Closing via https://github.com/fossasia/susi_skill_cms/pull/300
