### ISSUE TITLE
Add a skill sorting option

### ISSUE THREAD

**Issue by isuruAb** [fossasia/susi_skill_cms#306]
**Actual Behaviour**

There is no any sorting option in skill browser.

**Expected Behaviour**

Give option to sort by ascending and descending orders  and order by date etc.

**Would you like to work on the issue?**

anyone can get it

**Comment by CodHeK** [comment]
I would like to work on this

**Comment by isuruAb** [comment]
@CodHeK  yes you can work on it. Read this doc to know about the end points you need to use for this case.
https://github.com/fossasia/susi_skill_cms/blob/master/docs/ServerEndPoints.md

cheers happy coding 👍

**Comment by tstreamDOTh** [comment]
@CodHeK are you still working on it? @isuruAb Can I work on this?

**Comment by isuruAb** [comment]
@tstreamDOTh  yes you can work
