### ISSUE TITLE
Searching feature in Skills CMS

### ISSUE THREAD

**Issue by akash1997** [fossasia/susi_skill_cms#322]
**Actual Behaviour**

Selecting a category and language, we need to click the search button to look at that particular category.

**Expected Behavior**

Selecting a category should automatically take you to the particular category. No need to press the search button every time.

**Would you like to work on the issue?**

I am new to Web Development, so it would take some time to understand, but I think I would be able to work on it.

**Comment by RMCoder198** [comment]
@akash1997 Are you still working on this issue?

**Comment by akash1997** [comment]
@RMCoder198 Yes, I'm working on it.

**Comment by jajodiaraghav** [comment]
Hi @akash1997 Can I claim this issue in case you aren't working?
Thanks

**Comment by akash1997** [comment]
@jajodiaraghav I had exams so I couldn't work on it, but now I'm working on this.

**Comment by jajodiaraghav** [comment]
I am claiming this issue as no update was made for past month.

**Comment by jajodiaraghav** [comment]
Please close this issue as the feature has already been implemented. The contributor should've mentioned this issue in his PR so that this could be closed earlier.
