### ISSUE TITLE
Navigation sidebar for categories & language

### ISSUE THREAD

**Issue by tstreamDOTh** [fossasia/susi_skill_cms#323]
**Actual Behaviour**
Presently, to view skills of a category, the user needs to select the category listed in a drop down and click submit button.

**Expected Behaviour**
Left Navigation sidebar with links to categories where the user can directly click to view the skills.

**Steps to reproduce it**
File: BrowseSkill.js
Changes: Refactor the modules, add helper functions, manage states for categories(groupValue) .

**Suggested Layout**
![image](https://user-images.githubusercontent.com/11137394/30247103-5a55f6b0-9629-11e7-9ddb-0aa42cd45de8.png)

Please give your feedback on the layout.

**Would you like to work on the issue?**

Yes. I would like to work on the issue.

**Comment by tstreamDOTh** [comment]
@mariobehling Should we have a side navbar? What do you think about the mockup?

**Comment by mariobehling** [comment]
Yes, the search functionality needs to be improved, but there are already improvements, e.g. you can click on categories without having to hit the search button.

**Comment by akshatnitd** [comment]
I am working on it

**Comment by anshumanv** [comment]
Let's complete https://github.com/fossasia/susi_skill_cms/issues/475 after this is done.
