### ISSUE TITLE
All components of SUSI are moving to https - Please change API requests to https

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#324]
Currently we are switching all components to https and there are some temporary issues e.g. "Load unsafe scripts" needs to be activated. 

Please also switch API requests and other components to request data through https.

![screenshot from 2017-09-14 17-40-42](https://user-images.githubusercontent.com/1583873/30439413-f2579f7a-9973-11e7-8b4f-37b05b3fd772.png)

**Comment by dynamitechetan** [comment]
Working on it 👍
