### ISSUE TITLE
AuthorSkillJS: Github URL hardcoded, instead use api

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#326]
In AuthorSkill.js, BrowseSkill.js, SkillEditor.js and other files the Github URL of the skill images are hardcoded.

> let image = 'https://raw.githubusercontent.com/fossasia/susi_skill_data/master/models/general/

Instead the skill image should come from the API server. The API server should be configured in a configuration file. It should not be hardcoded.

**Comment by dynamitechetan** [comment]
@mariobehling opened https://github.com/fossasia/susi_server/issues/564 on SUSI Server.

**Comment by codejockie** [comment]
I'm a newbie, can I handle this?

**Comment by tstreamDOTh** [comment]
Would like to work on it.

**Comment by akshatnitd** [comment]
The skill images are now fetched from the server. Hence, closing.
