### ISSUE TITLE
Sort languages in the same way as Wikipedia

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#328]
Please sort languages in the same way as Wikipedia.

![screenshot from 2017-09-16 03-58-33](https://user-images.githubusercontent.com/1583873/30508284-790b4ef2-9a93-11e7-8350-96f2685e9849.png)

**Comment by tstreamDOTh** [comment]
I would like to work on this issue. 👍

**Comment by DravitLochan** [comment]
@tstreamDOTh  Ok. Please make a relevant PR.

**Comment by jajodiaraghav** [comment]
Hi, I think the issue is fixed. Can we close this?

**Comment by tstreamDOTh** [comment]
@mariobehling This can be closed?
