### ISSUE TITLE
Enhance category and search display

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#329]
Please enhance categories as follows:
* add a field "All" to show results of all categories.
* As soon as the user selects a category, show results of that category without requiring the user to click on the search button
* Provide an additional search field on the left in front of the "category" field where the user can type in. Results should be displayed immediately similar to the web app of open event compare for example here: https://sched.eventyay.com/PyCon2017/schedule.html
* Take out the button "->"

![screenshot from 2017-09-16 04-22-45](https://user-images.githubusercontent.com/1583873/30508403-b72fbc06-9a96-11e7-9bcb-099336540146.png)

**Comment by tstreamDOTh** [comment]
@mariobehling Have implemented the render skill cards without click feature and also refactored the code to make it easy to implement further enhancements. 
For the search feature do we need to implement search within the category or all skills?

**Comment by AnupKumarPanwar** [comment]
@mariobehling This issue can be closed now.
