### ISSUE TITLE
Show "all skills" on start page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#333]
Recent PRs resulted in an empty start page. Skills are not showing up anymore. Expected: All skills should show up on the start page.

* On top dropdown show "All" skills
* On the start page show all skills listed

![screenshot from 2017-09-19 10-01-00](https://user-images.githubusercontent.com/1583873/30581801-b473625a-9d21-11e7-8a58-b506a21655fa.png)

**Comment by shashank-sharma** [comment]
I guess it is happening because of null parameters which are present in this link: https://api.susi.ai/cms/getSkillList.json?applyFilter=true&filter_name=ascending&filter_type=lexicographical
Which causes BrowseSkill.js to crash. I am looking how it can be solved

**Comment by mariobehling** [comment]
This issue is not solved. Show "All" in categories is not implemented.

**Comment by tstreamDOTh** [comment]
@mariobehling Currently, when the initial cards are loaded a request is made to  **https://api.susi.ai/cms/getSkillList.json?applyFilter=true&filter_name=ascending&filter_type=lexicographical** 
This returns skills under "Knowledge" category only. 
And when the category is exclusively selected as "Knowledge" and the on submit button click again skills under "Knowledge" category are listed but there is a discrepancy of no. of skills returned. 

I tried to implement it but then "All" category will only show skills returned from **https://api.susi.ai/cms/getSkillList.json?applyFilter=true&filter_name=ascending&filter_type=lexicographical** but then these skills are from knowledge skills only which is forcing to hardcode the category value to get images for "All Category". I don't find this as a good practice. For this, it would be better if skill JSON has group value in it. 

Please give your suggestions.

**Comment by shashank-sharma** [comment]
@tstreamDOTh I also looked this thing. I even tried to analyze the susi-api-server to see if 'All' category is available or not but it was not present. I guess we need to edit and add that 'all' feature in api server.

**Comment by tstreamDOTh** [comment]
@shashank-sharma I feels the same. Else the other way is to individually get skills of each group and add into skill list but it is not possible with the existing code structure since we can only have one state for the groupValue.

**Comment by mariobehling** [comment]
@shashank-sharma @tstreamDOTh Please open an issue on SUSI Server and help to follow up and implement it.

**Comment by tstreamDOTh** [comment]
@mariobehling Opened the issue on SUSI Server, will follow-up.
