### ISSUE TITLE
Do not show "Save" button and editing functions for anonymous users who cannot save edits

### ISSUE THREAD

**Issue by tabesin** [fossasia/susi_skill_cms#336]
**Actual Behaviour**

When editing a skill non-logged in you can proceed till the save button which then shows you an error message reminding you to log in.

**Expected Behaviour**

* Show the page only as a non-editable version similar to Wikipedia pages, that cannot be edited, e.g. https://en.wikipedia.org/w/index.php?title=Israel&action=edit. 

* Do not show a "Save" button.

**Steps to reproduce it**

(you are not logged in)
1 https://skills.susi.ai/Knowledge/ceo/en
2. Button edit leads you to https://skills.susi.ai/Knowledge/ceo/edit/en
3. You edit something. Eg. change the description of the skill.
4. You add a commit description and hit "save"
5. You get an error message asking you to log in
6. The change is kept present in your cms anyway.

**Screenshots of the issue**

![bildschirmfoto vom 2017-09-20 10-12-12](https://user-images.githubusercontent.com/10114907/30633532-468ded84-9dec-11e7-8330-5bd5fd9d373e.png)

**Comment by Remorax** [comment]
I would like to take this up :)

**Comment by saurabhjn76** [comment]
Sure go ahead @Remorax !!

**Comment by akshatnitd** [comment]
Closing, since already fixed.
