### ISSUE TITLE
After saving a skill redirect automatically to skill page

### ISSUE THREAD

**Issue by hpdang** [fossasia/susi_skill_cms#338]
Currently when I save a skill the "Save" button changes to "Saving". Expected is, that it shows "Saving" as of now, but it should redirect to Skill Page immediately.

![Uploading Screenshot from 2017-09-22 11-22-58.png…]()

**Comment by tstreamDOTh** [comment]
@hpdang I would like to work on it.

**Comment by DravitLochan** [comment]
@tstreamDOTh please go ahead and make a pr.

**Comment by tstreamDOTh** [comment]
@DravitLochan Yes, made the PR.
