### ISSUE TITLE
Changing example does not substitute old example on skill page

### ISSUE THREAD

**Issue by hpdang** [fossasia/susi_skill_cms#339]
After update the skill example, the skill page continues to show the older/previous example instead of only showing the updated example.

Expected: Only show the actual example from the code pad.

![screenshot from 2017-09-22 16-31-15](https://user-images.githubusercontent.com/1658742/30749429-b02f8626-9fb3-11e7-9a06-8b2987845813.png)

**Comment by dynamitechetan** [comment]
@hpdang   I just tested this and it works. Probably you just went back in your browser and the new page was not loaded. Please try to refresh the skill page after editing the skill.

**Comment by tstreamDOTh** [comment]
@dynamitechetan I was able to recreate the bug.
