### ISSUE TITLE
Skill edit error

### ISSUE THREAD

**Issue by agbilotia1998** [fossasia/susi_skill_cms#348]
**Actual Behaviour**

When the name of any skill is edited , a new skill is getting created.

**Expected Behaviour**

No new skill should be created instead modifications must be made to skill being edited.

**Steps to reproduce it**
Edit name of any skill and check details for the skill.
**Screenshots of the issue**
![screenshot from 2017-10-07 19-13-21](https://user-images.githubusercontent.com/21157929/31308463-eb338672-ab94-11e7-9fa3-28e37d001939.png)

**Would you like to work on the issue?**
Yes
Please let us know if you can work on it or the issue should be assigned to someone else.

**Comment by akshatnitd** [comment]
This has been resolved.
