### ISSUE TITLE
Add option "All" in Category Tab 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#356]
The category tab is missing an "All" option to show all available skills. Please add this option on top to show "all skills".

**Comment by tstreamDOTh** [comment]
@mariobehling This is not implemented on the server. Issue on server #587.

**Comment by akshatnitd** [comment]
I would like to work on it

**Comment by AnupKumarPanwar** [comment]
Should I take this issue as no progress is there towards it for a long time?

**Comment by AnupKumarPanwar** [comment]
@mariobehling  I think that this issue can be closed now.

**Comment by akshatnitd** [comment]
Closing, since already fixed.
