### ISSUE TITLE
Add Loader in main page

### ISSUE THREAD

**Issue by S2606** [fossasia/susi_skill_cms#357]
**Actual Behaviour**

Currently nothing happens when site loads

**Expected Behaviour**

A small loader named 'loading skills' can be added

**Would you like to work on the issue?**

Yes

**Comment by gaurang444** [comment]
I would like to work on it.Please provide some details.

**Comment by S2606** [comment]
@gaurang444 Sorry to say but i am working in this.

**Comment by ParthS007** [comment]
any updates @S2606. I would like to work on it

**Comment by S2606** [comment]
@ParthS007 I currently have exams.Would send PR in few days..

**Comment by gaurang444** [comment]
Bro you are taking too long;

**Comment by harshit98** [comment]
@S2606 Let the new comers try to solve the issue. @gaurang444 Please go ahead. Let me know if you're stuck somewhere.

**Comment by mariobehling** [comment]
Not needed.
