### ISSUE TITLE
Adding image for skill results in error message -> Cannot create skill

### ISSUE THREAD

**Issue by pepebecker** [fossasia/susi_skill_cms#358]
When ever I'm trying to commit a new skill, I get this error message:

<img width="534" alt="screen shot 2017-11-12 at 22 11 45" src="https://user-images.githubusercontent.com/6045310/32703493-15d2ebce-c7f7-11e7-9963-1ad8219491b7.png">

It says that it is supposed to be a **JPG** image

There are three errors here:
* It should allow any image as in the existing skills, e.g. png. So the error message itself is wrong
* It should work without an image and take a placeholder image of the system. It does neither work without adding an image.
* Also it does not automatically insert the image url into the `::image` field.

**Comment by tstreamDOTh** [comment]
@pepebecker Thanks for reporting. Would work on it.

**Comment by akshatnitd** [comment]
This has been resolved. Hence, closing.
