### ISSUE TITLE
Documentation needed for deployment using Surge

### ISSUE THREAD

**Issue by ParthS007** [fossasia/susi_skill_cms#362]
**Actual Behaviour**

Presently there is no clear direction that how to provide deployment link using surge

**Expected Behaviour**

There should be proper directions for deployment so that new contributors don't find face any problem while deploying using surge.

**Would you like to work on the issue?**

YES

**Comment by aashutoshrathi** [comment]
@ParthS007 Take a look at https://github.com/fossasia/susper.com/pull/828, it would be better if same could be done here.

**Comment by ParthS007** [comment]
I will try to do that :+1:
