### ISSUE TITLE
Add author image in author skills section in SUSI.AI Skill CMS. We will use github avatar of author

### ISSUE THREAD

**Issue by madhavrathi** [fossasia/susi_skill_cms#364]
**Actual Behaviour**

Every skill has an author and clicking on author gives list of all skills made by that author. We have linked author's github account.

**Expected Behaviour**

We can show author's avatar too in author's section using Github's API.

**Would you like to work on the issue?**
This is a GCI task. Anyone participating in GCI can take this up.

**Comment by harsh-jindal** [comment]
@madhavrathi I would like to work on this. Can you be more clear on where do you want the author's avatar to be shown?(Like a screenshot )

**Comment by madhavrathi** [comment]
@harsh-jindal Author's avatar should be same as their GitHub avatar.

**Comment by sayak119** [comment]
@madhavrathi may I take up this issue due to lack of any activity ?

**Comment by sayak119** [comment]
I am taking up this issue due to inactivity.
