### ISSUE TITLE
Improve sort functionality

### ISSUE THREAD

**Issue by tstreamDOTh** [fossasia/susi_skill_cms#366]
**Actual Behaviour**

On selection, of sort filter, the text is not changing.

**Expected Behaviour**

Use appropriate labels.

**Screenshots of the issue**

![screen shot 2017-12-03 at 12 39 59 am](https://user-images.githubusercontent.com/11137394/33518875-89eb921a-d7c2-11e7-95a5-79431e19161e.png)
![screen shot 2017-12-03 at 12 39 55 am](https://user-images.githubusercontent.com/11137394/33518876-8a4c6f7c-d7c2-11e7-8637-98acac238c8a.png)

**Would you like to work on the issue?**

Yes

**Comment by Remorax** [comment]
Are you still working on this, @tstreamDOTh or can I take it up?

**Comment by tstreamDOTh** [comment]
@Remorax Will make a PR
