### ISSUE TITLE
404 Error on clicking SUSI Skill tutorial in README

### ISSUE THREAD

**Issue by Remorax** [fossasia/susi_skill_cms#368]
**Actual Behaviour**

When the SUSI Skill Language tutorial link is clicked in the README, it gives a 404 Error.

**Expected Behaviour**

It should link to the tutorial file.

**Steps to reproduce it**

1. Go to the README.
2. Click on the "SUSI Skill Language" link in the Learn Skill Language section.
3. We get a 404 error.

**Screenshots of the issue**

![screen shot 2017-12-17 at 5 09 28 pm](https://user-images.githubusercontent.com/26062692/34079123-18475644-e34d-11e7-9281-82e399407be5.png)
![screen shot 2017-12-17 at 5 09 34 pm](https://user-images.githubusercontent.com/26062692/34079124-1887ee2a-e34d-11e7-9dd6-335ff8332e5a.png)

**Would you like to work on the issue?**

Yes, I would like to work on this issue. This is a small issue, but nevertheless I feel its' important :)

**Comment by anshumanv** [comment]
Merged, please close. :smile:
