### ISSUE TITLE
Invalid Images on susi skill page

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi_skill_cms#388]
**Actual Behaviour**

All the images on main page of susi skills are invalid.

**Expected Behaviour**

They should be corrected.

**Screenshots of the issue**

<img width="600" alt="screen shot 2018-02-16 at 10 25 45 pm" src="https://user-images.githubusercontent.com/31174685/36319356-ad2f9672-1368-11e8-931c-e29126a3ab85.png">

**Would you like to work on the issue?**

Yes

**Comment by DNS-404** [comment]
@saurabhjn76 These images are not present in the location where they should be. Rather they are present in another subfolder within the "Knowledge" folder in susi_skill_data.
For example - URL for image for AboutSusi skill should be https://raw.githubusercontent.com/fossasia/susi_skill_data/master/models/general/Knowledge/en/images/aboutsusi.png as per the code but actually it is https://raw.githubusercontent.com/fossasia/susi_skill_data/master/models/general/Knowledge/id/images/language.png/aboutsusi.png
So in this case, should I cut and paste all images to the location specified in code? Or should I change the location of images in code?
Please help.

**Comment by saurabhjn76** [comment]
@DNS-404 Please update the code as per new location of the images. 👍
