### ISSUE TITLE
Link for submitting skills to git tutorial not working.

### ISSUE THREAD

**Issue by manishv123** [fossasia/susi_skill_cms#407]
Actual Behaviour

https://github.com/fossasia/susi_skill_cms/blob/master/docs/submitting_skills_to_git.md is not working.

Expected Behaviour

It should open the webpage to display the tutorial in order to submit skills to susi permanently.

Steps to reproduce it

Go to link https://github.com/fossasia/susi_skill_cms/blob/master/docs/submitting_skills_to_git.md

Screenshots of the issue
![screenshot 123](https://user-images.githubusercontent.com/30909295/37563836-6eb09a96-2aaf-11e8-9da8-4a14f2f5b85b.png)

Would you like to work on the issue?
Yes

**Comment by anshumanv** [comment]
Not valid anymore.
