### ISSUE TITLE
Clicking on the thumbs up/down icon redirects to that elements page

### ISSUE THREAD

**Issue by SudhanvaMG** [fossasia/susi_skill_cms#408]
**Actual Behaviour**

In the Skills page , when you click on the thumbs up/down icon , it redirects to the elements page 

**Expected Behaviour**

When the icon is clicked , the value should be incremented and it should not redirect 

**Steps to reproduce it**

Go to https://skills.susi.ai/ and go the the skills tab . Click on any of the thumbs up/down icon on the cards.

**Comment by stealthanthrax** [comment]
I'd like to work on this issue
