### ISSUE TITLE
Error on running locally

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_skill_cms#414]
**Actual Behaviour**

When this repo is cloned, and run locally by `npm install` and then `npm start`, it doesnot work. Error is shown on the console and the browser:
![image](https://user-images.githubusercontent.com/17807257/39650757-144fdfbc-5007-11e8-83fd-3d9b98179a7d.png)
(these functions are defined, but are arrow functions)
**Steps to reproduce it**
1. Clone this repo locally. (make a new clone if you already have it previously)
2. run `npm install`.
3. run `npm start`.

**Would you like to work on the issue?**
I tried to figure out what is wrong, but couldn't find it. If anyone is facing similar problem, please help.

**Comment by stealthanthrax** [comment]
@hkedia321 , its working for me.

**Comment by anshumanv** [comment]
Still not fixed? :thinking:

**Comment by hkedia321** [comment]
Working fine now locally.
