### ISSUE TITLE
No Icons in Login/SignUp form

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/susi_skill_cms#449]
**Actual Behaviour**

Currently, there are no icons in Login/Signup form on https://skills.susi.ai

**Expected Behaviour**

There should be icons accompanying the Email TextField, and the Password Field.

**Screenshots of the issue**
This is how the form currently looks like : 
![signupskillssusiai](https://user-images.githubusercontent.com/31135861/39993955-5cd1f35c-5795-11e8-9780-7f8bd19dec4f.png)

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Please see here: https://github.com/fossasia/susi_skill_cms/pull/450#issuecomment-390715368 Thank you.
