### ISSUE TITLE
Use the ratings api to list skills as per their ratings

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_skill_cms#460]
**Actual Behaviour**
Follow up of https://github.com/fossasia/susi_server/issues/724 once the APIs are implemented we need to show the ratings for each skill on skill card as well as the skill page

**Expected Behaviour**
Display it in the metrics section as after #459 .

**Would you like to work on the issue?**
Yes, I'll work on it

**Comment by mariobehling** [comment]
Please check out how Google is doing it, e.g. here https://developers.google.com/actions/distribute/directory

**Comment by anshumanv** [comment]
@mariobehling this is the current implementation in my pull https://github.com/fossasia/susi_skill_cms/pull/470 - 

![image](https://user-images.githubusercontent.com/21009455/40291528-1a2404a2-5ce3-11e8-8ea1-c37b5a329aa7.png)

Please suggest if any changes are required.
