### ISSUE TITLE
Travis autodeployment fails

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_skill_cms#471]
**Actual Behaviour**
Auto deployment is failed due to some missing modules

**Expected Behaviour**
It should work and deploy to the gh-pages branch

**Steps to reproduce it**
https://travis-ci.org/fossasia/susi_skill_cms check the build

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/21009455/40304506-9ab38418-5d14-11e8-8e30-df4bd296f204.png)

**Would you like to work on the issue?**
Trying to figure you to make the build work

**Comment by anshumanv** [comment]
Working on this at priority.

**Comment by akshatnitd** [comment]
@anshumanv It can be closed, as it is already solved

**Comment by anshumanv** [comment]
Yes, thanks @akshatnitd :smile:
