### ISSUE TITLE
Add option to Sort by latest skills, top used skills, highest rated skills

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_skill_cms#475]
**Actual Behaviour**
There is no such option in the Sort By option.

**Expected Behaviour**
Sort by Latest Skills, Top Used Skills and Highest Rated Skills should be added

**Would you like to work on the issue?**
Yes. It can be done once the PRs for rating system is merged.

**Comment by anshumanv** [comment]
Will update the PR today after getting autodeployment fixed.

**Comment by akshatnitd** [comment]
@anshumanv Go ahead with it, working on some other issues as of now

**Comment by anshumanv** [comment]
This needs modification to the getAllSKills endpoint and I think @AnupKumarPanwar is working on it, will complete this once endpoint is ready.

**Comment by anshumanv** [comment]
Working on top rated.
