### ISSUE TITLE
Make changes in the Skills Card on SUSI Skills home page

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_skill_cms#485]
**Actual Behaviour**
It shows hands-up/down rating

**Expected Behaviour**
Change it to the 5-star rating system.

**Steps to reproduce it**
Go to http://susi.skills.ai

**Screenshots of the issue**
* Actual
![screenshot from 2018-05-24 09-40-48](https://user-images.githubusercontent.com/12656846/40464079-97b7f4e6-5f36-11e8-893a-4a4553182b60.png)

* Expected
![screenshot from 2018-05-24 09-41-02](https://user-images.githubusercontent.com/12656846/40464082-9aee4638-5f36-11e8-9884-469155fac465.png)

**Would you like to work on the issue?**
Yes

**Comment by anshumanv** [comment]
@akshatnitd I'd like to help on this. :smile:

**Comment by akshatnitd** [comment]
Looking to implement https://github.com/fossasia/susi_server/issues/743, so that we can work on this issue :smile:
