### ISSUE TITLE
Close icon for SUSI chatbot isn't visible

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi_skill_cms#490]
**Current Behaviour**

There should be a "close" icon on top right corner of chatbot. It's not visible.
<img width="441" alt="screen shot 2018-05-24 at 3 38 14 pm" src="https://user-images.githubusercontent.com/31174685/40479214-b1236154-5f68-11e8-81bf-565bbad9d058.png">

**Would you like to work on the issue?**
Yes

**Comment by DNS-404** [comment]
@hkedia321 @anshumanv @PrP-11 @akshatnitd @Akshat-Jain @arundhati24
Can any of you guys please copy this script and paste it any html file to see if this is just with me or is this really not visible?
```
<script type="text/javascript" src="https://skills.susi.ai/susi-chatbot.js"></script>
```

**Comment by hkedia321** [comment]
@DNS-404 Its coming fine in Google Chrome and Mozilla Firefox (60.0.1).
![image](https://user-images.githubusercontent.com/17807257/40487172-f0a0edc0-5f80-11e8-886b-89412ff77908.png).

**Comment by DNS-404** [comment]
Thanks. I tested in Safari and Google Chrome. It's not working in both of them..
Can someone else also please test it?

**Comment by anshumanv** [comment]
Works for me too :thinking:

**Comment by DNS-404** [comment]
Weird..
Okay thanks for testing. I'm closing this issue. I'll find out what's wrong in my system :/

**Comment by akshatnitd** [comment]
@DNS-404 It also appear for me initially. On close look, I found it, but was faintly visible due to lack of contrasting background. Opened an issue #492 for it.
