### ISSUE TITLE
Skills don't appear when we choose "All" category

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi_skill_cms#491]
**Actual Behaviour**

No skills appear on choosing "All" category.

**Expected Behaviour**

It should show all the skills.

**Screenshots of the issue**
<img width="600" alt="screen shot 2018-05-24 at 7 56 59 pm" src="https://user-images.githubusercontent.com/31174685/40491913-ed4d66ce-5f8c-11e8-9242-7b920a3362d3.png">

**Would you like to work on the issue?**

Yes

**Comment by anshumanv** [comment]
@DNS-404 please follow - https://github.com/fossasia/susi_skill_cms/pull/472

**Comment by DNS-404** [comment]
@anshumanv Okay. Sorry. Didn't see 😅
