### ISSUE TITLE
Close button for SUSI chatbot plugin is very faint

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_skill_cms#492]
**Actual Behaviour**

Close button for SUSI chatbot plugin is very faint

**Expected Behaviour**

Change the icon to a prominent one with contrasting background. 

**Steps to reproduce it**
Open SUSI chatbot plugin

**Screenshots of the issue**

![deepinscreenshot_select-area_20180524220723](https://user-images.githubusercontent.com/12656846/40499368-57b9838c-5f9f-11e8-9695-6f293b8b6581.png)

**Would you like to work on the issue?**
Yes

**Comment by DNS-404** [comment]
@akshatnitd Are you still working on this? 😅 
I'm thinking about redesigning the whole chatbot. This one is causing some errors and it can be improved.
Here's the issue - https://github.com/fossasia/susi_skill_cms/issues/503

**Comment by akshatnitd** [comment]
@DNS-404 Yes, have sent a PR #504. You can redesign the rest of the UI :)
