### ISSUE TITLE
Dropdown menu not always aligned to burger bar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#493]
The dropdown menu is not always aligned in different screen sizes on Chrome.

Please help to fix it.

![screenshot from 2018-05-25 00-06-34](https://user-images.githubusercontent.com/1583873/40516238-2af82860-5fb0-11e8-9e4c-279f960d1a45.png)

**Comment by anshumanv** [comment]
Working on it.

**Comment by anshumanv** [comment]
This is an issue only when the user is logged in, investigating.

**Comment by DNS-404** [comment]
@anshumanv Maybe this is due the Email ID showing up after logging in.
