### ISSUE TITLE
Add support for different type of responses in the conversational bot plugin

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_skill_cms#498]
**Actual Behaviour**

Only `answer` type of action is supported in the conversational bot web-plugin.

**Expected Behaviour**

Support the following type of `action` as well:
- table
- anchor
- image

**Would you like to work on the issue?**

Yes.

**Comment by anshumanv** [comment]
@hkedia321 sounds promising, but where do you implement this exactly? :thinking:

**Comment by hkedia321** [comment]
@anshumanv for the SUSI web chat plugin. It supports only simple text based response for now, so we need to add support for remaining type of responses as well. Changed the title now :+1:
