### ISSUE TITLE
Odd positioning of SUSI logo in the susi plugin

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_skill_cms#502]
**Actual Behaviour**

Currently, when I am integrating SUSI plugin on my website, the SUSI logo is in an odd place

**Expected Behaviour**

To improve the positioning of the SUSI logo

**Screenshots of the issue**
<img width="1276" alt="screen shot 2018-05-25 at 3 19 58 pm" src="https://user-images.githubusercontent.com/29942790/40538654-e6d7f37e-602f-11e8-97b3-92c6c4db16de.png">

**Would you like to work on the issue?**
This issue can be assigned to anyone

**Comment by DNS-404** [comment]
I'd like to work on this. Thanks for testing.
