### ISSUE TITLE
Add a profile page where each user can see the skills they have created and get aggregated stats

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_skill_cms#506]
**Actual Behaviour**
No profile page is present for logged in user

**Expected Behaviour**
Once the user is logged in we can have a page where the user can see the skills they created and several aggregated statistics on those skills like total upvotes, downvotes, average rating, total users that rated their skill etc.

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
This should be added to the /dashboard.

**Comment by anshumanv** [comment]
Sure will add this in the /dashboard route.
