### ISSUE TITLE
Travis autodeployment fails

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_skill_cms#508]
**Actual Behaviour**
Travis autodeployment fails

**Expected Behaviour**
http://skills.susi.ai should be up and running

**Steps to reproduce it**
Open http://skills.susi.ai

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
@saurabhjn76 @isuruAb From this https://github.com/fossasia/susi_skill_cms/commit/0ff6c601d9495f7909730dcf3e59ae5c435cadb6, i can been seen that nothing was committed on last build. Can you help running the Travis build again!

**Comment by saurabhjn76** [comment]
@akshatnitd Done

**Comment by akshatnitd** [comment]
@anshumanv @mariobehling https://skills.susi.ai/ is up and running again. Restarting the build worked. There was some error in fetching one of the package, while the last build took place, which led to the failed deployment.

Thanks @saurabhjn76 !
Closing the issue :+1:
