### ISSUE TITLE
Missing slash in the API URL

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_skill_cms#521]
**Actual Behaviour**

A slash is missing in the fiveStarRateSkill.json API URL which causes 404 not found error.

**Expected Behaviour**

The API URL should be correct.

**Steps to reproduce it**

1. Go to https://skills.susi.ai/
2. Open any skill page and try rating it.
3. Trace the network call.

```
The call is made to the following URL

https://api.susi.aicms/fiveStarRateSkill.json?model=general&group=Knowledge&language=en&skill=aboutsusi&rating=4&callback=pc&_=1527533991092
```

**LogCat for the issue**

NA

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/10573038/40627160-01776e64-62db-11e8-982c-1fdcafb579e6.png)

**Would you like to work on the issue?**

Yes, but before that the following issue needs to be resolved.
[Change storing of 5-star rating mapping to email #751](https://github.com/fossasia/susi_server/issues/751)

**Comment by anshumanv** [comment]
Please close.

**Comment by akshatnitd** [comment]
Closing, since already fixed.
