### ISSUE TITLE
Create Menu options for botbuilder

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi_skill_cms#530]
**Expected Behaviour**

Menu options need to be created for "Builder", "Design", "Metrics" and "Deploy" as shown in these mockups [here](https://docs.google.com/presentation/d/17ZDpfV3IM7azCTl3yGVd8e7aw_zX4mArs8Wdbw0o-6Y/edit?usp=sharing).

**Would you like to work on the issue?**

Yes

**Comment by DNS-404** [comment]
The screen would look something like this now:
<img width="577" alt="screen shot 2018-05-31 at 12 49 46 am" src="https://user-images.githubusercontent.com/31174685/40746631-90ad8d04-6478-11e8-9a24-b7151363be5e.png">

**Comment by DNS-404** [comment]
The menu bar won't be blue because top bar is blue.

**Comment by mariobehling** [comment]
Please add "Publish" into the same line with the "Builder" menu.

**Comment by DNS-404** [comment]
Okay :+1:

**Comment by DNS-404** [comment]
@hkedia321 is working on it here https://github.com/fossasia/susi_skill_cms/issues/544.
I'll work on the menu tabs by making its UI better like earlier.
