### ISSUE TITLE
5 Star skill rating is not working

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_skill_cms#531]
**Actual Behaviour**

The 5 star skill rating system is not working. Errors are produced.

**Expected Behaviour**

The skill should be rated properly.

**Steps to reproduce it**

Try rating any skill on the SUSI Skill CMS.

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
@AnupKumarPanwar This issue is an duplicate of #509. I was waiting for the backend APIs to work as expected before

**Comment by AnupKumarPanwar** [comment]
@akshatnitd Ok I've sent a PR for these issues. https://github.com/fossasia/susi_skill_cms/pull/534. Kindly review.

**Comment by anshumanv** [comment]
Please close.

**Comment by akshatnitd** [comment]
Closing, since already fixed.
