### ISSUE TITLE
Create the first version of builder page for BotBuilder

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi_skill_cms#543]
**Expected Behaviour**

In the first version of builder page, bot creator would create skills that are labelled "private" the same way skills are created as of now. There won't be any pictorial representation.
These skills will be stored in susi_skill_data for now. This needs to be implemented on server as well. We need API to provide us private skill of a user(bot creator) when logged in(using `access_token`).

**Mockup**

Bot creator would be able to add multiple private skills for his/her bot which would be shown in a list. There would be a "+" button for adding new skill and after adding the skill it would be added to the list in tabular form.

List and "+" button -
<img width="1022" alt="screen shot 2018-05-31 at 8 37 11 pm" src="https://user-images.githubusercontent.com/31174685/40790406-7a69a98e-6512-11e8-9728-c36846c5130e.png">

Creation process -
<img width="1026" alt="screen shot 2018-05-31 at 8 20 05 pm" src="https://user-images.githubusercontent.com/31174685/40789519-3697d174-6510-11e8-8b46-f93c0fe1249c.png">

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Ok, looks good as work in progress. Although I am unclear what is on the "analytics" tab. 

The top bar should include "deploy" on the right.

**Comment by DNS-404** [comment]
@mariobehling Here's the issue for "Analytics" tab -https://github.com/fossasia/susi_skill_cms/issues/535. It has a mockup of what'll be on it.
Okay, I'll move "Deploy" to top bar on the right. "Preview" would be under it.

**Comment by mariobehling** [comment]
Please don't confuse a dashboard with a wizard. We need a wizard to create a bot. What are the steps for a wizard? It should probably be like that:
**Step 1:** Click on + button on start page and choose from two option a) Create Skill (Public) and b) Create Skill Bot

![screenshot from 2018-06-02 02-51-34](https://user-images.githubusercontent.com/1583873/40858545-2cd8e8ba-6611-11e8-908c-f164ffa2c7e0.png)

**Step 2.** A screen shows up with the menu: Build - Design - Configure - Deploy.
The easiest to start with is to create the bot in the "code view" for now. 

<img width="1022" alt="botbuilder" src="https://user-images.githubusercontent.com/1583873/40858685-b96dbefe-6611-11e8-924e-1a70782117b2.png">

Then follow up in next steps in following issues/PRs.

**Comment by DNS-404** [comment]
@mariobehling Is clicking on "Create Skill Bot" redirecting bot creator to the `botbuilder` page?

**Comment by mariobehling** [comment]
Yes, correct.

And we also need a page "My Skills" similar to this one below. However you should also mark in the table if a skill is private or public.

<img width="1022" alt="myskills" src="https://user-images.githubusercontent.com/1583873/40859035-f1f584ea-6612-11e8-93f1-65eedb9cf5da.png">

**Comment by mariobehling** [comment]
Clicking on the + button should always result in two options. Please understand that the "gray area" only shows up when the user clicks on the button.

**Comment by DNS-404** [comment]
Wouldn't it make more sense to display only private skills in "My Skills", because there's already a complete list of public skills available?

**Comment by mariobehling** [comment]
We follow existing systems like Wikipedia, where a user can get a list of their contributions. However, the difference is that we have private skills. Before we go into long discussions about "edge cases" and questions "what if lots of other options are needed" please solve the basics now.
