### ISSUE TITLE
Bugs in theme settings need to be fixed

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/susi_skill_cms#568]
**Actual Behaviour**

Currently, the theme settings have a few bugs.

**Expected Behaviour**

The bugs need to be fixed.

**Steps to reproduce it**

Go to https://skills.susi.ai and login. Then change theme from Light to Dark. Now again try changing theme from Dark to Light. You'll see that it doesn't work as expected as the Light option is already selected and it gives you the option to switch to Dark theme only.

**Would you like to work on the issue?**

Yes

**Comment by Akshat-Jain** [comment]
![themesettingsbug](https://user-images.githubusercontent.com/31135861/40884581-d9d0beda-6733-11e8-9862-aa81d7bf3dc5.gif)

**Comment by Akshat-Jain** [comment]
@stealthanthrax Please check the GIF above. Thanks :-)

**Comment by stealthanthrax** [comment]
Thanks @Akshat-Jain 👍

**Comment by mariobehling** [comment]
We should focus on functionality at this point. Can we get rid of the theme in the skills cms, please? We should not waste time on making this work. Changing themes will not bring us more users as a feature at this point. Please take out the theme functionality.

**Comment by Akshat-Jain** [comment]
@mariobehling Okay, I'm on it.

**Comment by Akshat-Jain** [comment]
@mariobehling Opened an issue for removing theme feature (https://github.com/fossasia/susi_skill_cms/issues/575). Hence, closing this issue as this is no longer required.
