### ISSUE TITLE
Give users three view options in "Build" for BotBuilder

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi_skill_cms#576]
**Expected Behaviour**

We're going to give users three view options in step 1 (Build) of bot building process.
These three view options are-
- Code view: In this view, user will type write code to create private skills for bot. This is just how public skills are created at the moment.
- Conversational view: In this view, user will be able to see how the conversation will undergo. See mockups to understand better.
- Tree view: In this view, user will be able to see graphically how the conversation will undergo. See mockups to understand better.

**Mockups**

*Conversational View:*
When user chooses option 1-
<img width="667" alt="screen shot 2018-06-04 at 10 48 26 am" src="https://user-images.githubusercontent.com/31174685/40899611-7628ad04-67e5-11e8-88ee-a9e80ebcbf3f.png">
When user chooses option 2-
<img width="665" alt="screen shot 2018-06-04 at 10 49 32 am" src="https://user-images.githubusercontent.com/31174685/40899612-7748d0b0-67e5-11e8-80ac-6de99c433e07.png">
So you can see that conversational view will basically **show** you how the actual conversation will undergo in all the different cases.

*Tree View:*
Now the same conversation in tree view will be shown like this:
![jun-04-2018 10-52-02](https://user-images.githubusercontent.com/31174685/40899681-cbde1f9a-67e5-11e8-9016-e1858ca598f2.gif)

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Looks good to me. Please make code view work first.

**Comment by DNS-404** [comment]
@mariobehling ,
@hkedia321 is working on code view(just the frontend part)(issue https://github.com/fossasia/susi_skill_cms/issues/543). So, I'm shifting my focus to this.
Once frontend of code view is done, then both of us will focus on it's backend.
For it's backend, for now, I think we should just add two parameters to all skills. Here's the issue for that - https://github.com/fossasia/susi_skill_data/issues/325. Please tell me if I should do it or not.
