### ISSUE TITLE
Datatype jsonp is used in API calls

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_skill_cms#581]
**Actual Behaviour**
Currently, all API calls use datatype jsonp

**Expected Behaviour**
Change jsonp to json

**Would you like to work on the issue?**
Yes

**Comment by hkedia321** [comment]
@akshatnitd can you please help me understand why is it needed to change all the `jsonp` to `json`?

**Comment by akshatnitd** [comment]
@hkedia321 Earlier the domain was different for the API as that of the client. So, `jsonp` was used, now since the domains are same, i.e, `susi.ai`. We can have it working without an overhead to AJAX calls that is caused by `jsonp`.

Also, for reference - 

> JSONP, which stands for "JSON with Padding" (and JSON stands for JavaScript Object Notation), is a way to get data from another domain that bypasses CORS (Cross Origin Resource Sharing) rules. CORS is a set of "rules," about transferring data between sites that have a different domain name from the client. ... Enter JSONP.
