### ISSUE TITLE
Top bar not responsive for mobile view

### ISSUE THREAD

**Issue by PrP-11** [fossasia/susi_skill_cms#583]
**Actual Behaviour**
Top bar is not responsive for mobile view

**Expected Behaviour**
It should be responsive

**Steps to reproduce it**
Open skills.susi.ai on mobile.
**Screenshots of the issue**
![b1](https://user-images.githubusercontent.com/30981465/40921234-808378dc-682c-11e8-9095-f45a2462ba3a.png)

**Would you like to work on the issue?**
Yes

**Comment by DNS-404** [comment]
How about you remove Email ID in mobile view? 🤔
