### ISSUE TITLE
Implement the Textual Feedback on the skill.

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_skill_cms#600]
**Actual Behaviour**

Currently the user is not textual feedback system is not implemented on the CMS.

**Expected Behaviour**

A user should be able to send textual feedback on the skills from the server.
The server side API has been implemented in this PR (https://github.com/fossasia/susi_server/pull/787)

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
Working on it
