### ISSUE TITLE
Skill names in dashboard should be links.

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_skill_cms#654]
**Actual Behaviour**
Skill names in dashboard should be links

**Expected Behaviour**
They are plain text.

**Would you like to work on the issue?**
Yes

**Comment by anshumanv** [comment]
@hkedia321 since you worked on the dashboard, do you think if this is a good idea? :thinking: 
The user will then be able to redirect to the skill page using this.

**Comment by hkedia321** [comment]
@anshumanv Yes, this will be an excellent feature. Please go ahead with this.

**Comment by anshumanv** [comment]
Thanks for your input, I was unsure if we need this before.
