### ISSUE TITLE
Integrate code editor with etherpad to run dreams

### ISSUE THREAD

**Issue by saurabhjn76** [fossasia/susi_skill_cms#66]
To run the code on susi_skill_cms editor we need to integrate it with etherpad.

**Comment by dynamitechetan** [comment]
In my opinion, this can be done in 2 ways. 
1. Integrate etherpad API directly and use dream.susi.ai for testing dreams.
2. Create an API endpoint on the server that accepts the text of the skill and Susi can give replies based on those skills.

**Comment by Orbiter** [comment]
I don't think that we should use an etherpad at all. The susi skill cms ist just a traditional cms with wiki-editing style in mind. So there is no question on how to add the etherpad.

**Comment by dynamitechetan** [comment]
How can we make the code/text editor work? 
The goal here that people can edit the skill and see the output side by side. 
please give your suggestions.

**Comment by saurabhjn76** [comment]
@Orbiter  @dynamitechetan  Shall we create some endpoint where we will pass the whole text written by the user and then these rules will be available to susi_server for processing?

**Comment by saurabhjn76** [comment]
No more relevant hence closing.
