### ISSUE TITLE
Set an Interval for evaluating the search query to reduce server load

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_skill_cms#665]
**Actual Behaviour**
Presently just as a search field value is changed an API call is made to the server to fetch the skills instantaneously which increases the network usage and server load by huge amounts

**Expected Behaviour**
We can provide an interval after any change is done like 300ms after which we go to the server and fetch the results as per the query.

**Would you like to work on the issue?**
Yes.

**Comment by Orbiter** [comment]
Does that mean that if I type a search word in the search box that subsequent character types with a time distance below 300 milliseconds does not cause an API query?

Or does that mean that every key will be delayed by 300 milliseconds?

**Comment by anshumanv** [comment]
Just as a change is detected in the input field it will query the server for the input value, so say I query `github` so the app will query the server for g, gi, git, gith, githu, github and then once we stop and the data is fetched results are shown, what I've simply done is the change event will only query the server once no change is detected in the input for 300ms, so if I type `github` with time less than 300ms between subsequent key strokes, so it will only query the server once for `github` and we will have our results.
