### ISSUE TITLE
Show actual skill usage data

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_skill_cms#685]
**Actual Behaviour**

Currently the CMS shows sample data in skill usage stats. 

**Expected Behaviour**

After PR [#793](https://github.com/fossasia/susi_server/pull/793) on server got merged. We can show the actual data from the API.

**Steps to reproduce it**

Check the Analytics of any skill on the CMS

**LogCat for the issue**

NA

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/10573038/41248613-352746c2-6dcf-11e8-8c9c-9f26bbb1688c.png)

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
Closing, since already fixed.
