### ISSUE TITLE
Optimisation: Add image preloading to speed up load time of index page

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_skill_cms#716]
**Actual Behaviour**
Since we have a lot of skills and all of the skills contain images it takes a lot of time to load all those images and then the page is loaded

**Expected Behaviour**
We should have image preloading to speed up the load time.

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
This is low priority for now. The site will still change a lot. Please focus on getting the features working.
