### ISSUE TITLE
The skills are displayed in an up down order in safari

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_skill_cms#730]
**Actual Behaviour**

The skills are not properly aligned and are not properly viewed in the safari browser, check screenshot

**Expected Behaviour**

The skills should be displayed in a properly aligned manner as in google chrome.

**Screenshots of the issue**

![screen shot 2018-06-15 at 11 36 31 am](https://user-images.githubusercontent.com/16780496/41452858-3db481fa-7091-11e8-8501-d991e2e2ee08.png)

**Would you like to work on the issue?**

@anshumanv and @DNS-404 may take this up

**Comment by akshatnitd** [comment]
The issue doesn't seem to exist as the UI has been completely revamped. Hence, closing.
