### ISSUE TITLE
The skills are not sorted and categorised

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_skill_cms#731]
**Actual Behaviour**

On selecting any category and sort by option the skills are not displayed in the sorted order and according to the category.

**Expected Behaviour**

They should be sorted and displayed according to the category and the chosen sort by option.

**Steps to reproduce it**

Open CMS and select any category and choose any sort by option.

**Would you like to work on the issue?**

Someone else may work on it

**Comment by akshatnitd** [comment]
It has already been fixed.
