### ISSUE TITLE
Clicking on "Create Skills" opens very slowly

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#734]
Please help to keep the system speedy. Clicking on "Create Skills" is very slowly opening the options. Please speed it up as fast as possible.

![screenshot from 2018-06-15 18-59-54](https://user-images.githubusercontent.com/1583873/41480332-6ce2c3c8-70ce-11e8-91fa-c865423ffa5c.png)

**Comment by Akshat-Jain** [comment]
I'll work on this.
