### ISSUE TITLE
Improve Top Skills View

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_cms#753]
The start page currently does not show skills sorted as top skills correctly. 

Please also change the "Top List Skills" as the standard view in the UI.

![screenshot from 2018-06-16 13-30-31](https://user-images.githubusercontent.com/1583873/41498275-a2cad8b8-7169-11e8-98a1-40d0dbe7bfb3.png)

**Comment by AnupKumarPanwar** [comment]
@mariobehling The skills are beings sorted correctly in decreasing order of the average star rating on the skills.
