### ISSUE TITLE
Implement skill sorting by their usage count.

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_skill_cms#769]
Implement an option in drop down menu to sort the skill in decreasing order of their usage count.
Refer to this server side issue : [Skill sorting by "most used first" order #842](https://github.com/fossasia/susi_server/issues/842)

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
@AnupKumarPanwar already created a issue here: https://github.com/fossasia/susi_skill_cms/issues/756

**Comment by akshatnitd** [comment]
Closing, since merged.
