### ISSUE TITLE
Implement Login page UI similar to chat.susi login page

### ISSUE THREAD

**Issue by PrP-11** [fossasia/susi_skill_cms#775]
**Actual Behaviour**
UI for chat.susi and skills are different

**Expected Behaviour**
It should be similar to login page of chat.susi

**Screenshots of the issue**

Login page of skills:
![l2](https://user-images.githubusercontent.com/30981465/41518299-3191fbfa-72df-11e8-872b-f259503ec69d.png)

Login page of chat.susi:
![l1](https://user-images.githubusercontent.com/30981465/41518312-3f2542e0-72df-11e8-8caa-2fe6a94ba39c.png)

**Would you like to work on the issue?**
Yes

**Comment by Akshat-Jain** [comment]
@PrP-11 It has been 15 days since this issue has been open. Can I proceed with this if you are not working on this?

**Comment by PrP-11** [comment]
@Akshat-Jain Sorry for the delay. I will send a PR related to this issue today itself. Thanks
