### ISSUE TITLE
Many images fail to load on home screen

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_skill_cms#780]
**Actual Behaviour**
Many images fail to load on home screen

**Expected Behaviour**
The skill images should load for all.

**Steps to reproduce it**
Open https://skills.susi.ai

**Screenshots of the issue**
![screenshot from 2018-06-18 23-56-07](https://user-images.githubusercontent.com/12656846/41554841-99cd2bf8-7353-11e8-9bbd-2a677a7e7132.png)

**Would you like to work on the issue?**
Yes

**Comment by akshatnitd** [comment]
This error was caused by this commit - https://github.com/fossasia/susi_skill_data/commit/d213e712d4c89b107ca7625ee1219837bb3fff06 by @prateekiiest

**Comment by akshatnitd** [comment]
Fixed by fossasais/susi_skill_data#334

**Comment by isuruAb** [comment]
Close this issue since it has solved
