### ISSUE TITLE
Can't edit skills or check details of skills

### ISSUE THREAD

**Issue by isuruAb** [fossasia/susi_skill_cms#785]
**Actual Behaviour**

Can't edit or check details of the skills. it does not render any details on the page after the loading screen.
**Expected Behaviour**

It should show skill details and should be able to edit skills.

**Screenshots of the issue**

<img width="1279" alt="screen shot 2018-06-19 at 8 41 25 am" src="https://user-images.githubusercontent.com/7692626/41573949-dc6a074e-739c-11e8-97e5-b947a9132174.png">

**Would you like to work on the issue?**

no

**Comment by anshumanv** [comment]
This happens sometimes due to some server issue, can you reload the page and check again?

**Comment by isuruAb** [comment]
Yes, It works. sometimes it works but sometimes not. I got this again.
<img width="1197" alt="screen shot 2018-06-21 at 10 38 08 am" src="https://user-images.githubusercontent.com/7692626/41699040-5f8444fc-753f-11e8-99b5-991bcdc07ae9.png">
