### ISSUE TITLE
Search is not working smoothly on the CMS

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_skill_cms#806]
**Actual Behaviour**

The focus from app bar is lost after typing a character.

**Expected Behaviour**

User should be able to type the search query smoothly.

**Steps to reproduce it**

Type a search query of the SUSI Skill CMS

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
Already merged.
