### ISSUE TITLE
Make a route to display Category wise skills

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_skill_cms#843]
**Actual Behaviour**
Not present

**Expected Behaviour**
Make a route to display Category wise skills

**Steps to reproduce it**
NA

**Would you like to work on the issue?**
Yes

**Comment by fragm3** [comment]
@akshatnitd please check before taking up a new issue https://github.com/fossasia/susi_skill_cms/pull/766

This has already been implemented, after the sidebar, it has some conflicts. Please fix the side bar, rest is done

**Comment by akshatnitd** [comment]
@fragm3 I see that this is a duplicate one, will close it. Also, what I see is #766 aims to solve multiple issues. The PR should have been divided into multiple PRs. KIndly fix the conflicts as soon as the sidebar is done, so that we can go ahead with the development.
