### ISSUE TITLE
Add CAPTCHA in sign up page

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_skill_cms#845]
**Actual Behaviour**

Not present

**Expected Behaviour**

Add captcha in skills sign up page

For chat.susi.ai: https://github.com/fossasia/chat.susi.ai/issues/1344

Would you like to work on the issue?

Yes

**Comment by anshumanv** [comment]
@fragm3 progress?

**Comment by fragm3** [comment]
@anshumanv the sign up page needs to be updated like chat-susi before we add captcha as css is overlapping somewhere.

**Comment by fragm3** [comment]
Will proceed with this when https://github.com/fossasia/susi_skill_cms/pull/1462 gets merged
