### ISSUE TITLE
Fix drop down menu content.

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_skill_cms#853]
**Actual Behaviour**

The drop-down menu content is horizontally scrollable.

**Expected Behaviour**

The drop down menu should appear properly.

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/10573038/41822030-30382c2a-7807-11e8-97a1-33b1049ff28a.png)

**Would you like to work on the issue?**

Yes

**Comment by anshumanv** [comment]
Working on this
