### ISSUE TITLE
Redesign the Category Wise Skill Page

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_skill_cms#859]
**Actual Behaviour**
* It currently uses BrowseSkill component.

**Expected Behaviour**
* The component needs to be implemented afresh and the UI should look like this - [Link](https://www.amazon.com/s/ref=lp_13727921011_nr_n_0?fst=as%3Aoff&rh=n%3A13727921011%2Cn%3A%2113727922011%2Cn%3A14284819011&bbn=13727922011&ie=UTF8&qid=1529866174&rnid=13727922011)

- [x] Make the sidebar as shown on the link.
- [ ] Design the Cards as shown on the link.
- [x] Make the page layout as shown on the link.

**Would you like to work on the issue?**
@anshumanv @AnupKumarPanwar and I would take this up.
Please comment on which subparts you would be working on.

**Comment by anshumanv** [comment]
@akshatnitd good pick, working on enhancing the sidebar like alexa, we probably need another expandedSkillCardList component for categories page which has skill image, 2 examples, author name, rating and desc for the skill which will be rendered on visiting any category.

Once the sidebar and this new expandedSkillCardList component is done, we can work on aligning the UI.
