### ISSUE TITLE
Display horizontal scroll button only when skills are successfully fetched

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_skill_cms#866]
**Actual Behaviour**
They are displayed everytime even when an error occurs while fetching skill data.

**Expected Behaviour**
Should be only available when skills are successfully fetched.

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/21009455/41890640-fbfd4954-792d-11e8-88f7-16ed5f91bd0f.png)

**Would you like to work on the issue?**
Yes

**Comment by akshatnitd** [comment]
It has already been taken care of in #854

**Comment by anshumanv** [comment]
Okay, didn't recognize multiple changes apart from the stated issue, closing. :+1:
