### ISSUE TITLE
Search is not working on the home page

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_skill_cms#925]
**Actual Behaviour**

No search results appear if searched on the home page.

**Expected Behaviour**

Search bar should work as it works on the category page.

**Steps to reproduce it**

Try to search anything on the CMS homepage.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/10573038/42167992-62ddda9a-7e2d-11e8-8784-b1fda13c662f.png)

**Would you like to work on the issue?**

Yes

**Comment by anshumanv** [comment]
@AnupKumarPanwar I didn't see your issue before and went ahead and solved it, please can you take care of #934 instead?

**Comment by Akshat-Jain** [comment]
@AnupKumarPanwar I think this can be closed now. It has been solved already. Hence, closing it. Thanks :-)
