### ISSUE TITLE
Update metrics section headers to the ones like alexa

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_skill_cms#936]
**Actual Behaviour**
They are plain like `Top Skills` etc

**Expected Behaviour**
They should be like alexa i.e - `SUSI, What are your top skills?`

**Would you like to work on the issue?**
Yes

**Comment by akshatnitd** [comment]
Can you do it for Top Used Skill in this PR itself ?

**Comment by anshumanv** [comment]
Yes @akshatnitd that is the plan. :+1:
