### ISSUE TITLE
Scrolling through cards on CMS homepage should scroll all cards present on screen

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/susi_skill_cms#937]
**Actual Behaviour**

Currently, scrolling through cards on the CMS homepage isn't scrolling through an entire card. We're left somewhere in the middle of 2 cards which isn't desired.
Based on the reviews on https://github.com/fossasia/susi_skill_cms/pull/874, it was supposedly fixed, but apparently the issue still remains.

**Expected Behaviour**

Clicking on either of the 2 arrows should scroll through all the cards present on the screen, just like how it's done on Alexa.

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
Please update the issue and implement scrolling of the cards that are present on the screen, instead of scrolling just one card. Check Alexa for reference. Thanks!

**Comment by anshumanv** [comment]
Ref - #911

**Comment by anshumanv** [comment]
@Akshat-Jain please give proper references to the parent issues so everything's at one place.
