### ISSUE TITLE
Metric cards don't show up towards the end of horizontal scroll on CMS Homepage on different screen sizes

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/susi_skill_cms#946]
**Actual Behaviour**

The horizontal scroll for the different metrics don't scroll up till the end of the metric cards for different screen sizes. This issue has been there since the horizontal scroll has been implemented for the different metrics (https://github.com/fossasia/susi_skill_cms/pull/850).

**Expected Behaviour**

We should be able to scroll through all the metrics irrespective of the screen size.

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
Please work on it on higher priority.

**Comment by Akshat-Jain** [comment]
@akshatnitd Sure. I'll send a PR for it asap. Thanks :-)
