### ISSUE TITLE
Show all skills on dashboard of admin

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi_skill_cms#987]
**Expected Behaviour**

We need to show all skills on the dashboard of admin with an option to mark to a skill as reviewed or non-reviewed.
Issue in server: https://github.com/fossasia/susi_server/issues/933

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
The skill dashboard of admins should be different to the usual user dashboard if possible, e.g. at https://skills.susi.ai/admin/dashboard

We also need a way to assign a role "admin" to users in accounts.susi.ai.

**Comment by DNS-404** [comment]
Okay. I'll make a separate route for dashboard admin.

**Comment by mariobehling** [comment]
Sorry, reconsidering this: The dashboard for admins should simply be at https://skills.susi.ai/admin/ . Thanks.

**Comment by DNS-404** [comment]
Okay 😅
